## **Installing Necessary Libraries**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import calendar
import os

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## **Data Loading & Make ready for Preprocessing**

In [3]:
## Loading the data
path ='/content/drive/MyDrive/Rainfall/Data/3_Hourly_Rainfall_Data.csv'
df = pd.read_csv(path, low_memory=False)
df

,StationName,StationID,Latitude,Longitude,Year,Month,Time,1,2,3,...,22,23,24,25,26,27,28,29,30,31
0,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,0,0.6,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.8,0,0.0
1,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,3,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0,0.0
2,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,6,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,2,0,0.0
3,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,9,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.6,0,0.0
4,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,12,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,2.4,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69691,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,9,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0,0.0
69692,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,12,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0,0.0
69693,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,15,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0,0.0
69694,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,18,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0,0.0
69695,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,21,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0,0.0

In [4]:
# Melt the DataFrame into a long format
df_rain = pd.melt(df, id_vars=['StationName','StationID','Latitude','Longitude', 'Year', 'Month', 'Time'], var_name='Day', value_name='Rainfall')
df_rain

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Rainfall
0,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,0,1,0.6
1,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,3,1,0.0
2,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,6,1,0.0
3,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,9,1,0.0
4,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,12,1,0.0
...,...,...,...,...,...,...,...,...,...
2160571,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,9,31,0.0
2160572,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,12,31,0.0
2160573,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,15,31,0.0
2160574,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,18,31,0.0
2160575,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,21,31,0.0

In [5]:
## Find the datatypes of the columns
df_rain.dtypes

StationName    object
StationID       int64
Latitude       object
Longitude      object
Year            int64
Month           int64
Time            int64
Day            object
Rainfall       object
dtype: object

In [6]:
df_rain.shape

(2160576, 9)

In [7]:
# Find unique values in 'Month column
df_rain['StationName'].unique()

array(['Saidpur', 'Rangpur', 'Dinajpur', 'Sylhet', 'Bogura', 'Mymensingh',
       'Rajshahi', 'Srimangal', 'Tangail', 'Ishurdi', 'Dhaka',
       'Chuadanga', 'Faridpur', 'Sitakunda', 'Cumilla', 'Chandpur',
       'Jessore', 'Madaripur', 'Feni', 'Maijdee_court', 'Khulna',
       'Barishal', 'Satkhira', 'Bhola', 'Rangamati', 'Sandwip', 'Hatiya',
       'Ambagan(Ctg.)', 'Mongla', 'Patuakhali', 'Chittagong', 'Khepupara',
       'Kutubdia', "Cox'sBazar", 'Teknaf'], dtype=object)

In [8]:
# Count unique StationIDs
num_unique_station_name = df_rain['StationName'].nunique()

print(f"Count of unique Station IDs: {num_unique_station_name}")

Count of unique Station IDs: 35

In [9]:
# Find unique values in 'Year column
df_rain['StationID'].unique()

array([41858, 10208, 10120, 10705, 10408, 10609, 10320, 10724, 41909,
       10910, 11111, 41926, 11505, 11912, 11313, 11316, 11407, 11513,
       11805, 11809, 11604, 11704, 11610, 11706, 12007, 11916, 11814,
       41977, 41958, 12103, 11921, 12110, 11925, 11927, 11929])

In [10]:
# Count unique StationIDs
num_unique_station_ids = df_rain['StationID'].nunique()

print(f"Count of unique Station IDs: {num_unique_station_ids}")

Count of unique Station IDs: 35

In [11]:
# Find unique values in 'Month column
df_rain['Latitude'].unique()

array(['25Deg.47Mts.N', '25Deg.44Mts.N', '25Deg.39Mts.N', '24Deg.54Mts.N',
       '24Deg.51Mts.N', '24Deg.43Mts.N', '24Deg.22Mts.N', '24Deg.18Mts.N',
       '24Deg.15Mts.N', '24Deg. 8Mts.N', '23Deg.46Mts.N', '23Deg.39Mts.N',
       '23Deg.36Mts.N', '23Deg.35Mts.N', '23Deg.26Mts.N', '23Deg.16Mts.N',
       '23Deg.11Mts.N', '23Deg.10Mts.N ', '23Deg.2Mts.N', '22Deg.52Mts.N',
       '22Deg.47Mts.N', '22Deg.45Mts.N', '22Deg.43Mts.N', '22Deg.41Mts.N',
       '22Deg.32Mts.N', '22Deg.29Mts.N', '22Deg.26Mts.N', '22Deg.21Mts.N',
       '22Deg.20Mts.N', '22Deg.16Mts.N', '21Deg.59Mts.N', '21Deg.49Mts.N',
       '21Deg.26Mts.N', '20Deg.52Mts.N'], dtype=object)

In [12]:
# Count unique latitudes
num_unique_latitude = df_rain['Latitude'].nunique()

print(f"Count of unique latitudes: {num_unique_latitude}")

Count of unique latitudes: 34

In [13]:
# Find unique values in 'Month column
df_rain['Longitude'].unique()

array(['88Deg.53Mts.E', '89Deg.14Mts.E', '88Deg.41Mts.E', '91Deg.53Mts.E',
       '89Deg.22Mts.E', '90Deg.26Mts.E', '88Deg.42Mts.E', '91Deg.44Mts.E',
       '89Deg.55Mts.E', '89Deg.3Mts.E', '90Deg.23Mts.E', '88Deg.52Mts.E',
       '89Deg.51Mts.E', '91Deg.42Mts.E', '91Deg.11Mts.E', '90Deg.42Mts.E',
       '89Deg.10Mts.E', '90Deg.11Mts.E', '91Deg.25Mts.E', '91Deg.6Mts.E',
       '89Deg.32Mts.E', '90Deg.20Mts.E', '89Deg.5Mts.E', '90Deg.39Mts.E',
       '92Deg.12Mts.E', '91Deg.26Mts.E', '91Deg.49Mts.E', '89Deg.36Mts.E',
       '90Deg.14Mts.E', '91Deg.51Mts.E', '91Deg.56Mts.E', '92Deg.18Mts.E'],
      dtype=object)

In [14]:
df_rain['Longitude'].nunique()

32

In [15]:
# Select only the required columns and drop duplicate rows
unique_stations = df_rain[['StationName','StationID', 'Latitude', 'Longitude']].drop_duplicates()

# Reset index for a clean look (optional)
unique_stations = unique_stations.reset_index(drop=True)

# Display the result
print(unique_stations)

      StationName  StationID        Latitude      Longitude
0         Saidpur      41858   25Deg.47Mts.N  88Deg.53Mts.E
1         Rangpur      10208   25Deg.44Mts.N  89Deg.14Mts.E
2        Dinajpur      10120   25Deg.39Mts.N  88Deg.41Mts.E
3          Sylhet      10705   24Deg.54Mts.N  91Deg.53Mts.E
4          Bogura      10408   24Deg.51Mts.N  89Deg.22Mts.E
5      Mymensingh      10609   24Deg.43Mts.N  90Deg.26Mts.E
6        Rajshahi      10320   24Deg.22Mts.N  88Deg.42Mts.E
7       Srimangal      10724   24Deg.18Mts.N  91Deg.44Mts.E
8         Tangail      41909   24Deg.15Mts.N  89Deg.55Mts.E
9         Ishurdi      10910   24Deg. 8Mts.N   89Deg.3Mts.E
10          Dhaka      11111   23Deg.46Mts.N  90Deg.23Mts.E
11      Chuadanga      41926   23Deg.39Mts.N  88Deg.52Mts.E
12       Faridpur      11505   23Deg.36Mts.N  89Deg.51Mts.E
13      Sitakunda      11912   23Deg.35Mts.N  91Deg.42Mts.E
14        Cumilla      11313   23Deg.26Mts.N  91Deg.11Mts.E
15       Chandpur      11316   23Deg.16Mts.N  90Deg.42Mts.E
16        Jessore      11407   23Deg.11Mts.N  89Deg.10Mts.E
17      Madaripur      11513  23Deg.10Mts.N   90Deg.11Mts.E
18           Feni      11805    23Deg.2Mts.N  91Deg.25Mts.E
19  Maijdee_court      11809   22Deg.52Mts.N   91Deg.6Mts.E
20         Khulna      11604   22Deg.47Mts.N  89Deg.32Mts.E
21       Barishal      11704   22Deg.45Mts.N  90Deg.20Mts.E
22       Satkhira      11610   22Deg.43Mts.N   89Deg.5Mts.E
23          Bhola      11706   22Deg.41Mts.N  90Deg.39Mts.E
24      Rangamati      12007   22Deg.32Mts.N  92Deg.12Mts.E
25        Sandwip      11916   22Deg.29Mts.N  91Deg.26Mts.E
26         Hatiya      11814   22Deg.26Mts.N   91Deg.6Mts.E
27  Ambagan(Ctg.)      41977   22Deg.21Mts.N  91Deg.49Mts.E
28         Mongla      41958   22Deg.20Mts.N  89Deg.36Mts.E
29     Patuakhali      12103   22Deg.20Mts.N  90Deg.20Mts.E
30     Chittagong      11921   22Deg.16Mts.N  91Deg.49Mts.E
31      Khepupara      12110   21Deg.59Mts.N  90Deg.14Mts.E
32       Kutubdia      11925   21Deg.49Mts.N  91Deg.51Mts.E
33     Cox'sBazar      11927   21Deg.26Mts.N  91Deg.56Mts.E
34         Teknaf      11929   20Deg.52Mts.N  92Deg.18Mts.E

In [16]:
df_rain['Year'].unique()

array([2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023])

In [17]:
df_rain['Year'].nunique()

21

In [18]:
# Find unique values in 'Month column
df_rain['Month'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
# Find unique values in 'Day column
df_rain['Day'].unique()

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31'], dtype=object)

In [20]:
# Find data types 'Day column
df_rain['Day'].dtypes

dtype('O')

In [21]:
# Convert the Day column to numeric
df_rain['Day'] = pd.to_numeric(df_rain['Day'])
df_rain

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Rainfall
0,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,0,1,0.6
1,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,3,1,0.0
2,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,6,1,0.0
3,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,9,1,0.0
4,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,12,1,0.0
...,...,...,...,...,...,...,...,...,...
2160571,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,9,31,0.0
2160572,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,12,31,0.0
2160573,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,15,31,0.0
2160574,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,18,31,0.0
2160575,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,21,31,0.0

In [22]:
## Find the datatypes of the columns again
df_rain.dtypes

StationName    object
StationID       int64
Latitude       object
Longitude      object
Year            int64
Month           int64
Time            int64
Day             int64
Rainfall       object
dtype: object

In [23]:
# Find unique values in 'Time' column
df_rain['Time'].unique()

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [24]:
# Find unique values in 'Rainfall' column
df_rain['Rainfall'].unique()

array([0.6, 0.0, 1.0, ..., 85.4, 63.9, 71.4], dtype=object)

## **Handling Missing value and Unwanted Symbol**

In [25]:
## Count the number of '****' in the value column
df_rain['Rainfall'][df_rain['Rainfall'] == '*****'].count()

np.int64(21)

In [26]:
# Filter rows where 'Rainfall' is '*****'
rows_with_asterisks = df_rain[df_rain['Rainfall'] == '*****']

# Display the rows
rows_with_asterisks

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Rainfall
277151,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2006,12,21,4,*****
309245,Chandpur,11316,23Deg.16Mts.N,90Deg.42Mts.E,2006,4,15,5,*****
309246,Chandpur,11316,23Deg.16Mts.N,90Deg.42Mts.E,2006,4,18,5,*****
378941,Chandpur,11316,23Deg.16Mts.N,90Deg.42Mts.E,2006,4,15,6,*****
1426557,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2007,12,15,21,*****
1870966,Patuakhali,12103,22Deg.20Mts.N,90Deg.20Mts.E,2010,3,18,27,*****
1983881,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,3,29,*****
1983882,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,6,29,*****
1983883,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,9,29,*****
1983884,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,12,29,*****
1983885,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,15,29,*****
1983886,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,18,29,*****
1983887,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,21,29,*****
2053576,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,0,30,*****
2053577,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,3,30,*****
2053578,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,6,30,*****
2053579,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,9,30,*****
2053580,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,12,30,*****
2053581,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,15,30,*****
2053582,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,18,30,*****
2053583,Jessore,11407,23Deg.11Mts.N,89Deg.10Mts.E,2005,6,21,30,*****

In [27]:
# Filter rows where 'Rainfall' is '*****'
rows_with_asterisks = df_rain[df_rain['Rainfall'] == '*****']

# Group by 'StationName' and display the results
station_specific_results = rows_with_asterisks.groupby('StationName')

# Display results for each station
for station, data in station_specific_results:
    print(f"Station: {station}")
    print(data, '\n')

Station: Chandpur
       StationName  StationID       Latitude      Longitude  Year  Month  \
309245    Chandpur      11316  23Deg.16Mts.N  90Deg.42Mts.E  2006      4
309246    Chandpur      11316  23Deg.16Mts.N  90Deg.42Mts.E  2006      4
378941    Chandpur      11316  23Deg.16Mts.N  90Deg.42Mts.E  2006      4

        Time  Day Rainfall
309245    15    5    *****
309246    18    5    *****
378941    15    6    *****

Station: Jessore
        StationName  StationID       Latitude      Longitude  Year  Month  \
1426557     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2007     12
1983881     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
1983882     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
1983883     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
1983884     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
1983885     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
1983886     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
1983887     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
2053576     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
2053577     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
2053578     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
2053579     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
2053580     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
2053581     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
2053582     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6
2053583     Jessore      11407  23Deg.11Mts.N  89Deg.10Mts.E  2005      6

         Time  Day Rainfall
1426557    15   21    *****
1983881     3   29    *****
1983882     6   29    *****
1983883     9   29    *****
1983884    12   29    *****
1983885    15   29    *****
1983886    18   29    *****
1983887    21   29    *****
2053576     0   30    *****
2053577     3   30    *****
2053578     6   30    *****
2053579     9   30    *****
2053580    12   30    *****
2053581    15   30    *****
2053582    18   30    *****
2053583    21   30    *****

Station: Patuakhali
        StationName  StationID       Latitude      Longitude  Year  Month  \
1870966  Patuakhali      12103  22Deg.20Mts.N  90Deg.20Mts.E  2010      3

         Time  Day Rainfall
1870966    18   27    *****

Station: Teknaf
       StationName  StationID       Latitude      Longitude  Year  Month  \
277151      Teknaf      11929  20Deg.52Mts.N  92Deg.18Mts.E  2006     12

        Time  Day Rainfall
277151    21    4    *****

In [28]:
# To find the null values
df_rain.isnull().sum()

StationName        0
StationID          0
Latitude           0
Longitude          0
Year               0
Month              0
Time               0
Day                0
Rainfall       39264
dtype: int64

In [29]:
# Replace '*****' with NaN in the original DataFrame
df_rain.loc[df_rain['Rainfall'] == '*****', 'Rainfall'] = np.nan

In [30]:
# To find the null values
df_rain.isnull().sum()

StationName        0
StationID          0
Latitude           0
Longitude          0
Year               0
Month              0
Time               0
Day                0
Rainfall       39285
dtype: int64

In [31]:
# Step 2: Convert 'Rainfall' to numeric, coercing errors (turn non-numeric to NaN)
df_rain['Rainfall'] = pd.to_numeric(df_rain['Rainfall'], errors='coerce')

# Group by StationName, Month, Day, and Time, and calculate the mean for each group
rainfall_mean = df_rain.groupby(['StationName', 'Month', 'Day', 'Time'])['Rainfall'].transform('mean')

# Replace '*****' (NaN values) with the mean of the same station, month, day, and time
df_rain['Rainfall'] = df_rain['Rainfall'].fillna(rainfall_mean)

# Verify the result
print(df_rain)

        StationName  StationID       Latitude      Longitude  Year  Month  \
0           Saidpur      41858  25Deg.47Mts.N  88Deg.53Mts.E  2003      1
1           Saidpur      41858  25Deg.47Mts.N  88Deg.53Mts.E  2003      1
2           Saidpur      41858  25Deg.47Mts.N  88Deg.53Mts.E  2003      1
3           Saidpur      41858  25Deg.47Mts.N  88Deg.53Mts.E  2003      1
4           Saidpur      41858  25Deg.47Mts.N  88Deg.53Mts.E  2003      1
...             ...        ...            ...            ...   ...    ...
2160571      Teknaf      11929  20Deg.52Mts.N  92Deg.18Mts.E  2023     12
2160572      Teknaf      11929  20Deg.52Mts.N  92Deg.18Mts.E  2023     12
2160573      Teknaf      11929  20Deg.52Mts.N  92Deg.18Mts.E  2023     12
2160574      Teknaf      11929  20Deg.52Mts.N  92Deg.18Mts.E  2023     12
2160575      Teknaf      11929  20Deg.52Mts.N  92Deg.18Mts.E  2023     12

         Time  Day  Rainfall
0           0    1       0.6
1           3    1       0.0
2           6    1       0.0
3           9    1       0.0
4          12    1       0.0
...       ...  ...       ...
2160571     9   31       0.0
2160572    12   31       0.0
2160573    15   31       0.0
2160574    18   31       0.0
2160575    21   31       0.0

[2160576 rows x 9 columns]

In [32]:
# Check it again to  find the null values
df_rain.isnull().sum()

StationName        0
StationID          0
Latitude           0
Longitude          0
Year               0
Month              0
Time               0
Day                0
Rainfall       33872
dtype: int64

In [33]:
# Check rows where 'Rainfall' is still NaN after replacement
rows_with_nan = df_rain[df_rain['Rainfall'].isna()]

# If there are still rows with NaN, inspect them
rows_with_nan

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Rainfall
2021192,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,2,0,30,NaN
2021193,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,2,3,30,NaN
2021194,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,2,6,30,NaN
2021195,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,2,9,30,NaN
2021196,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,2,12,30,NaN
...,...,...,...,...,...,...,...,...,...
2160563,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,11,9,31,NaN
2160564,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,11,12,31,NaN
2160565,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,11,15,31,NaN
2160566,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,11,18,31,NaN
2160567,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,11,21,31,NaN

In [34]:
# Sample: Define valid days for each month (for non-leap years)
valid_days_per_month = {
    1: 31, 2: 28, 3: 31, 4: 30, 5: 31, 6: 30,
    7: 31, 8: 31, 9: 30, 10: 31, 11: 30, 12: 31
}

# Adjust for leap years (for February only)
def is_leap_year(year):
    return (year % 4 == 0 and (year % 100 != 0 or year % 400 == 0))

# Add a column to check if a year is a leap year
df_rain['IsLeapYear'] = df_rain['Year'].apply(is_leap_year)

# Adjust February days for leap years
df_rain.loc[df_rain['IsLeapYear'], 'ValidDays'] = df_rain.loc[df_rain['IsLeapYear'], 'Month'].apply(lambda month: 29 if month == 2 else valid_days_per_month[month])
df_rain.loc[~df_rain['IsLeapYear'], 'ValidDays'] = df_rain.loc[~df_rain['IsLeapYear'], 'Month'].apply(lambda month: valid_days_per_month[month])

In [35]:
# Remove rows where 'Day' is greater than the valid days for that month
df_rain = df_rain[df_rain['Day'] <= df_rain['ValidDays']]

In [36]:
df_rain

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Rainfall,IsLeapYear,ValidDays
0,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,0,1,0.6,False,31.0
1,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,3,1,0.0,False,31.0
2,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,6,1,0.0,False,31.0
3,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,9,1,0.0,False,31.0
4,Saidpur,41858,25Deg.47Mts.N,88Deg.53Mts.E,2003,1,12,1,0.0,False,31.0
...,...,...,...,...,...,...,...,...,...,...,...
2160571,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,9,31,0.0,False,31.0
2160572,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,12,31,0.0,False,31.0
2160573,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,15,31,0.0,False,31.0
2160574,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,18,31,0.0,False,31.0
2160575,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,21,31,0.0,False,31.0

In [37]:
# Check rows where 'Rainfall' is still NaN after replacement
rows_with_nan = df_rain[df_rain['Rainfall'].isna()]

# If there are still rows with NaN, inspect them
rows_with_nan

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Rainfall,IsLeapYear,ValidDays
2073512,Hatiya,11814,22Deg.26Mts.N,91Deg.6Mts.E,2004,12,0,30,NaN,True,31.0
2073513,Hatiya,11814,22Deg.26Mts.N,91Deg.6Mts.E,2004,12,3,30,NaN,True,31.0
2073514,Hatiya,11814,22Deg.26Mts.N,91Deg.6Mts.E,2004,12,6,30,NaN,True,31.0
2073515,Hatiya,11814,22Deg.26Mts.N,91Deg.6Mts.E,2004,12,9,30,NaN,True,31.0
2073516,Hatiya,11814,22Deg.26Mts.N,91Deg.6Mts.E,2004,12,12,30,NaN,True,31.0
...,...,...,...,...,...,...,...,...,...,...,...
2144995,Hatiya,11814,22Deg.26Mts.N,91Deg.6Mts.E,2023,7,9,31,NaN,False,31.0
2144996,Hatiya,11814,22Deg.26Mts.N,91Deg.6Mts.E,2023,7,12,31,NaN,False,31.0
2144997,Hatiya,11814,22Deg.26Mts.N,91Deg.6Mts.E,2023,7,15,31,NaN,False,31.0
2144998,Hatiya,11814,22Deg.26Mts.N,91Deg.6Mts.E,2023,7,18,31,NaN,False,31.0
2144999,Hatiya,11814,22Deg.26Mts.N,91Deg.6Mts.E,2023,7,21,31,NaN,False,31.0

In [38]:
# Check it again to  find the null values
df_rain.isnull().sum()

StationName      0
StationID        0
Latitude         0
Longitude        0
Year             0
Month            0
Time             0
Day              0
Rainfall       464
IsLeapYear       0
ValidDays        0
dtype: int64

In [39]:

# Group by StationName, Month, Day, and Time, and calculate the mean for each group
rainfall_mean = df_rain.groupby(['StationName', 'Month', 'Day', 'Time'])['Rainfall'].transform('mean')

# Replace '*****' (NaN values) with the mean of the same station, month, day, and time
df_rain['Rainfall'] = df_rain['Rainfall'].fillna(rainfall_mean)

# Verify the result
print(df_rain)

        StationName  StationID       Latitude      Longitude  Year  Month  \
0           Saidpur      41858  25Deg.47Mts.N  88Deg.53Mts.E  2003      1
1           Saidpur      41858  25Deg.47Mts.N  88Deg.53Mts.E  2003      1
2           Saidpur      41858  25Deg.47Mts.N  88Deg.53Mts.E  2003      1
3           Saidpur      41858  25Deg.47Mts.N  88Deg.53Mts.E  2003      1
4           Saidpur      41858  25Deg.47Mts.N  88Deg.53Mts.E  2003      1
...             ...        ...            ...            ...   ...    ...
2160571      Teknaf      11929  20Deg.52Mts.N  92Deg.18Mts.E  2023     12
2160572      Teknaf      11929  20Deg.52Mts.N  92Deg.18Mts.E  2023     12
2160573      Teknaf      11929  20Deg.52Mts.N  92Deg.18Mts.E  2023     12
2160574      Teknaf      11929  20Deg.52Mts.N  92Deg.18Mts.E  2023     12
2160575      Teknaf      11929  20Deg.52Mts.N  92Deg.18Mts.E  2023     12

         Time  Day  Rainfall  IsLeapYear  ValidDays
0           0    1       0.6       False       31.0
1           3    1       0.0       False       31.0
2           6    1       0.0       False       31.0
3           9    1       0.0       False       31.0
4          12    1       0.0       False       31.0
...       ...  ...       ...         ...        ...
2160571     9   31       0.0       False       31.0
2160572    12   31       0.0       False       31.0
2160573    15   31       0.0       False       31.0
2160574    18   31       0.0       False       31.0
2160575    21   31       0.0       False       31.0

[2121304 rows x 11 columns]

/tmp/ipython-input-1758615502.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rain['Rainfall'] = df_rain['Rainfall'].fillna(rainfall_mean)

In [40]:
# Check if all Rainfall values within each group are NaN
nan_groups = df_rain.groupby(['StationName', 'Month', 'Day', 'Time'])['Rainfall'].apply(lambda x: x.isna().all())

# Get the combinations that have all NaN Rainfall values
print(nan_groups[nan_groups].index)  # This will show you the groups where all Rainfall values are NaN

MultiIndex([('Hatiya',  7, 31,  0),
            ('Hatiya',  7, 31,  3),
            ('Hatiya',  7, 31,  6),
            ('Hatiya',  7, 31,  9),
            ('Hatiya',  7, 31, 12),
            ('Hatiya',  7, 31, 15),
            ('Hatiya',  7, 31, 18),
            ('Hatiya',  7, 31, 21),
            ('Hatiya', 12, 30,  0),
            ('Hatiya', 12, 30,  3),
            ('Hatiya', 12, 30,  6),
            ('Hatiya', 12, 30,  9),
            ('Hatiya', 12, 30, 12),
            ('Hatiya', 12, 30, 15),
            ('Hatiya', 12, 30, 18),
            ('Hatiya', 12, 30, 21),
            ('Hatiya', 12, 31,  0),
            ('Hatiya', 12, 31,  3),
            ('Hatiya', 12, 31,  6),
            ('Hatiya', 12, 31,  9),
            ('Hatiya', 12, 31, 12),
            ('Hatiya', 12, 31, 15),
            ('Hatiya', 12, 31, 18),
            ('Hatiya', 12, 31, 21)],
           names=['StationName', 'Month', 'Day', 'Time'])

In [41]:
# 1. Sort data to ensure time is sequential (Crucial for interpolation)
df_rain = df_rain.sort_values(by=['StationName', 'Year', 'Month', 'Day', 'Time'])

# 2. Interpolate missing values
# This fills the gap by drawing a line between the previous valid value and the next valid value
# Limit_direction='both' ensures it handles edges if necessary
df_rain['Rainfall'] = df_rain.groupby('StationName')['Rainfall'].transform(
    lambda x: x.interpolate(method='linear', limit_direction='both')
)

# 4. Final Verification
print("Remaining NaN values:", df_rain['Rainfall'].isnull().sum())

Remaining NaN values: 0

In [42]:
# Check it again to  find the null values
df_rain.isnull().sum()

StationName    0
StationID      0
Latitude       0
Longitude      0
Year           0
Month          0
Time           0
Day            0
Rainfall       0
IsLeapYear     0
ValidDays      0
dtype: int64

In [43]:
df_rain = df_rain.drop(columns=['IsLeapYear', 'ValidDays'])

In [44]:
df_rain

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Rainfall
54144,Ambagan(Ctg.),41977,22Deg.21Mts.N,91Deg.49Mts.E,2003,1,0,1,0.0
54145,Ambagan(Ctg.),41977,22Deg.21Mts.N,91Deg.49Mts.E,2003,1,3,1,0.0
54146,Ambagan(Ctg.),41977,22Deg.21Mts.N,91Deg.49Mts.E,2003,1,6,1,0.0
54147,Ambagan(Ctg.),41977,22Deg.21Mts.N,91Deg.49Mts.E,2003,1,9,1,0.0
54148,Ambagan(Ctg.),41977,22Deg.21Mts.N,91Deg.49Mts.E,2003,1,12,1,0.0
...,...,...,...,...,...,...,...,...,...
2160571,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,9,31,0.0
2160572,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,12,31,0.0
2160573,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,15,31,0.0
2160574,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,18,31,0.0
2160575,Teknaf,11929,20Deg.52Mts.N,92Deg.18Mts.E,2023,12,21,31,0.0

## **Coverting Latitude and Longitude to Numerical Value**

In [45]:
df_rain.dtypes

StationName     object
StationID        int64
Latitude        object
Longitude       object
Year             int64
Month            int64
Time             int64
Day              int64
Rainfall       float64
dtype: object

In [46]:
def convert_to_decimal(deg_min, direction):
    """
    Converts degree-minute format to decimal degrees.
    Example Input: "23Deg.46Mts.", "N" -> Output: 23.77
    """
    parts = deg_min.split("Deg.")
    degrees = float(parts[0])
    # split("Mts.")[0] ensures we get just the number part
    minutes = float(parts[1].split("Mts.")[0])

    decimal = degrees + (minutes / 60)

    # Convert South/West to negative
    if direction in ["S", "W"]:
        decimal = -decimal

    # Round to 4 decimal places
    return round(decimal, 4)

# Example usage
latitude = convert_to_decimal("23Deg.46Mts.", "N")
longitude = convert_to_decimal("90Deg.23Mts.", "E")

print(latitude, longitude)  # Output: 23.77, 90.38

23.7667 90.3833

In [47]:
df_rain["Latitude"] = df_rain["Latitude"].apply(lambda x: convert_to_decimal(x[:-1], x[-1]))  # Extract last character (N/S)
df_rain["Longitude"] = df_rain["Longitude"].apply(lambda x: convert_to_decimal(x[:-1], x[-1]))  # Extract last character (E/W)
df_rain

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Rainfall
54144,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,0,1,0.0
54145,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,3,1,0.0
54146,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,6,1,0.0
54147,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,9,1,0.0
54148,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,12,1,0.0
...,...,...,...,...,...,...,...,...,...
2160571,Teknaf,11929,20.8667,92.3000,2023,12,9,31,0.0
2160572,Teknaf,11929,20.8667,92.3000,2023,12,12,31,0.0
2160573,Teknaf,11929,20.8667,92.3000,2023,12,15,31,0.0
2160574,Teknaf,11929,20.8667,92.3000,2023,12,18,31,0.0
2160575,Teknaf,11929,20.8667,92.3000,2023,12,21,31,0.0

## **Creating Date Time Column**

In [48]:
# Check for invalid days (e.g., day > 31 or day > max days in the month)
invalid_dates = df_rain[(df_rain['Day'] > 31) | (df_rain['Month'] > 12)]
print(invalid_dates)

Empty DataFrame
Columns: [StationName, StationID, Latitude, Longitude, Year, Month, Time, Day, Rainfall]
Index: []

In [49]:
# 1. Define the expected standard times (3-hour intervals)
# Based on your data: 0, 3, 6, 9, 12, 15, 18, 21
expected_times = [0, 3, 6, 9, 12, 15, 18, 21]

# 2. Find rows where 'Time' is NOT in that list
# The ~ symbol means "NOT"
invalid_time_rows = df_rain[~df_rain['Time'].isin(expected_times)]

if not invalid_time_rows.empty:
    print("Found inconsistent Time values:")
    print(invalid_time_rows['Time'].unique()) # Show just the weird values found
    print("\nSample rows with invalid times:")
    print(invalid_time_rows[['StationName', 'Year', 'Month', 'Day', 'Time']].head())
else:
    print("All Time values are valid 3-hourly intervals.")

# 3. (Optional) Check for logic errors like Time > 23 or < 0
# This catches things like '25' or '-1' even if you weren't strictly enforcing 3-hour steps
logic_errors = df_rain[(df_rain['Time'] > 23) | (df_rain['Time'] < 0)]

if not logic_errors.empty:
    print("\nFound logical Time errors (Time > 23 or < 0):")
    print(logic_errors[['StationName', 'Year', 'Month', 'Day', 'Time']])

All Time values are valid 3-hourly intervals.

In [50]:
import calendar

# Function to check if a date is valid
def is_invalid_date(row):
    days_in_month = calendar.monthrange(row['Year'], row['Month'])[1]
    return row['Day'] > days_in_month

# Remove invalid rows
df_rain = df_rain[~df_rain.apply(is_invalid_date, axis=1)].reset_index(drop=True)

# Convert datetime again
df_rain['Datetime'] = pd.to_datetime(df_rain[['Year', 'Month', 'Day']]) + pd.to_timedelta(df_rain['Time'], unit='h')

print(df_rain.info())  # Verify that datetime is correctly created

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2121304 entries, 0 to 2121303
Data columns (total 10 columns):
 #   Column       Dtype
---  ------       -----
 0   StationName  object
 1   StationID    int64
 2   Latitude     float64
 3   Longitude    float64
 4   Year         int64
 5   Month        int64
 6   Time         int64
 7   Day          int64
 8   Rainfall     float64
 9   Datetime     datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(5), object(1)
memory usage: 161.8+ MB
None

In [51]:
df_rain

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Rainfall,Datetime
0,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,0,1,0.0,2003-01-01 00:00:00
1,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,3,1,0.0,2003-01-01 03:00:00
2,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,6,1,0.0,2003-01-01 06:00:00
3,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,9,1,0.0,2003-01-01 09:00:00
4,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,12,1,0.0,2003-01-01 12:00:00
...,...,...,...,...,...,...,...,...,...,...
2121299,Teknaf,11929,20.8667,92.3000,2023,12,9,31,0.0,2023-12-31 09:00:00
2121300,Teknaf,11929,20.8667,92.3000,2023,12,12,31,0.0,2023-12-31 12:00:00
2121301,Teknaf,11929,20.8667,92.3000,2023,12,15,31,0.0,2023-12-31 15:00:00
2121302,Teknaf,11929,20.8667,92.3000,2023,12,18,31,0.0,2023-12-31 18:00:00
2121303,Teknaf,11929,20.8667,92.3000,2023,12,21,31,0.0,2023-12-31 21:00:00

In [52]:
print(df_rain["Datetime"].apply(type).value_counts())

Datetime
<class 'pandas._libs.tslibs.timestamps.Timestamp'>    2121304
Name: count, dtype: int64

## **Handling Duplicates**

In [53]:
print(df_rain.duplicated().sum())  # Check for duplicate rows

143

In [54]:
# Find duplicate rows
duplicates = df_rain[df_rain.duplicated()]

# Show the duplicate rows
duplicates

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Rainfall,Datetime
1806947,Satkhira,11610,22.7167,89.0833,2020,7,3,1,0.0,2020-07-01 03:00:00
1806949,Satkhira,11610,22.7167,89.0833,2020,7,6,1,0.0,2020-07-01 06:00:00
1806951,Satkhira,11610,22.7167,89.0833,2020,7,9,1,0.0,2020-07-01 09:00:00
1806953,Satkhira,11610,22.7167,89.0833,2020,7,12,1,0.0,2020-07-01 12:00:00
1806957,Satkhira,11610,22.7167,89.0833,2020,7,18,1,0.0,2020-07-01 18:00:00
...,...,...,...,...,...,...,...,...,...,...
1807413,Satkhira,11610,22.7167,89.0833,2020,7,6,30,0.0,2020-07-30 06:00:00
1807415,Satkhira,11610,22.7167,89.0833,2020,7,9,30,0.0,2020-07-30 09:00:00
1807417,Satkhira,11610,22.7167,89.0833,2020,7,12,30,0.0,2020-07-30 12:00:00
1807421,Satkhira,11610,22.7167,89.0833,2020,7,18,30,0.0,2020-07-30 18:00:00
1807423,Satkhira,11610,22.7167,89.0833,2020,7,21,30,0.0,2020-07-30 21:00:00

In [55]:
# Save duplicate rows to a CSV file for manual inspection
duplicates.to_csv('duplicate_rows.csv', index=False)

print("Duplicates saved to 'duplicate_rows.csv'. Check your file directory.")

Duplicates saved to 'duplicate_rows.csv'. Check your file directory.

In [56]:
# Remove all duplicate rows (considering all columns)
df_rain = df_rain.drop_duplicates()

# Display the cleaned DataFrame
df_rain

,StationName,StationID,Latitude,Longitude,Year,Month,Time,Day,Rainfall,Datetime
0,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,0,1,0.0,2003-01-01 00:00:00
1,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,3,1,0.0,2003-01-01 03:00:00
2,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,6,1,0.0,2003-01-01 06:00:00
3,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,9,1,0.0,2003-01-01 09:00:00
4,Ambagan(Ctg.),41977,22.3500,91.8167,2003,1,12,1,0.0,2003-01-01 12:00:00
...,...,...,...,...,...,...,...,...,...,...
2121299,Teknaf,11929,20.8667,92.3000,2023,12,9,31,0.0,2023-12-31 09:00:00
2121300,Teknaf,11929,20.8667,92.3000,2023,12,12,31,0.0,2023-12-31 12:00:00
2121301,Teknaf,11929,20.8667,92.3000,2023,12,15,31,0.0,2023-12-31 15:00:00
2121302,Teknaf,11929,20.8667,92.3000,2023,12,18,31,0.0,2023-12-31 18:00:00
2121303,Teknaf,11929,20.8667,92.3000,2023,12,21,31,0.0,2023-12-31 21:00:00

In [57]:
print(df_rain.duplicated().sum())  # Check for duplicate rows

0

In [58]:
print(df_rain.groupby("StationID")["Datetime"].nunique())  # Check number of unique timestamps per station

StationID
10120    61360
10208    61360
10320    61360
10408    61360
10609    61360
10705    61360
10724    58440
10910    61360
11111    61360
11313    61360
11316    61360
11407    61360
11505    61360
11513    61360
11604    61360
11610    61120
11704    61360
11706    61360
11805    58440
11809    61360
11814    58424
11912    61360
11916    61360
11921    46752
11925    61360
11927    58440
11929    61360
12007    61360
12103    61360
12110    61360
41858    61360
41909    61360
41926    61360
41958    61360
41977    61360
Name: Datetime, dtype: int64

In [59]:
# Reorganizing columns
df_rain = df_rain[[
    'Datetime', 'StationName',
    'StationID', 'Latitude', 'Longitude',
    'Year', 'Month', 'Day', 'Time',
    'Rainfall'
]]

# Display the first few rows to confirm
df_rain.head()

,Datetime,StationName,StationID,Latitude,Longitude,Year,Month,Day,Time,Rainfall
0,2003-01-01 00:00:00,Ambagan(Ctg.),41977,22.35,91.8167,2003,1,1,0,0.0
1,2003-01-01 03:00:00,Ambagan(Ctg.),41977,22.35,91.8167,2003,1,1,3,0.0
2,2003-01-01 06:00:00,Ambagan(Ctg.),41977,22.35,91.8167,2003,1,1,6,0.0
3,2003-01-01 09:00:00,Ambagan(Ctg.),41977,22.35,91.8167,2003,1,1,9,0.0
4,2003-01-01 12:00:00,Ambagan(Ctg.),41977,22.35,91.8167,2003,1,1,12,0.0

## **Data Summary**

In [60]:
print(df_rain.info())  # Check data types and missing values
print(df_rain.describe())  # Summary statistics for numeric columns
print(df_rain["Datetime"].min(), df_rain["Datetime"].max())  # Verify datetime range
print(df_rain.duplicated().sum())  # Check for duplicate rows

<class 'pandas.core.frame.DataFrame'>
Index: 2121161 entries, 0 to 2121303
Data columns (total 10 columns):
 #   Column       Dtype
---  ------       -----
 0   Datetime     datetime64[ns]
 1   StationName  object
 2   StationID    int64
 3   Latitude     float64
 4   Longitude    float64
 5   Year         int64
 6   Month        int64
 7   Day          int64
 8   Time         int64
 9   Rainfall     float64
dtypes: datetime64[ns](1), float64(3), int64(5), object(1)
memory usage: 178.0+ MB
None
                            Datetime     StationID      Latitude  \
count                        2121161  2.121161e+06  2.121161e+06
mean   2013-07-28 07:29:41.846069504  1.580979e+04  2.332437e+01
min              2003-01-01 00:00:00  1.012000e+04  2.086670e+01
25%              2008-05-29 15:00:00  1.111100e+04  2.243330e+01
50%              2013-08-05 12:00:00  1.170600e+04  2.316670e+01
75%              2018-10-12 09:00:00  1.192900e+04  2.425000e+01
max              2023-12-31 21:00:00  4.197700e+04  2.578330e+01
std                              NaN  1.075368e+04  1.191547e+00

          Longitude          Year         Month           Day          Time  \
count  2.121161e+06  2.121161e+06  2.121161e+06  2.121161e+06  2.121161e+06
mean   9.046066e+01  2.013072e+03  6.519584e+00  1.572921e+01  1.049997e+01
min    8.868330e+01  2.003000e+03  1.000000e+00  1.000000e+00  0.000000e+00
25%    8.936670e+01  2.008000e+03  4.000000e+00  8.000000e+00  3.000000e+00
50%    9.038330e+01  2.013000e+03  7.000000e+00  1.600000e+01  9.000000e+00
75%    9.170000e+01  2.018000e+03  1.000000e+01  2.300000e+01  1.500000e+01
max    9.230000e+01  2.023000e+03  1.200000e+01  3.100000e+01  2.100000e+01
std    1.127700e+00  6.016735e+00  3.448789e+00  8.799889e+00  6.873854e+00

           Rainfall
count  2.121161e+06
mean   7.909741e-01
min    0.000000e+00
25%    0.000000e+00
50%    0.000000e+00
75%    0.000000e+00
max    9.990000e+01
std    4.286080e+00
2003-01-01 00:00:00 2023-12-31 21:00:00
0

In [61]:
# Option 1: Temporary fix for just this print
print(df_rain.describe().apply(lambda s: s.apply('{0:.2f}'.format)))

# Option 2: Global fix (Recommended)
# This tells pandas to always use 2 decimal places and no scientific notation
pd.options.display.float_format = '{:.2f}'.format

print(df_rain.describe())

         Datetime   StationID    Latitude   Longitude        Year       Month  \
count  2121161.00  2121161.00  2121161.00  2121161.00  2121161.00  2121161.00
mean          .2f    15809.79       23.32       90.46     2013.07        6.52
min           .2f    10120.00       20.87       88.68     2003.00        1.00
25%           .2f    11111.00       22.43       89.37     2008.00        4.00
50%           .2f    11706.00       23.17       90.38     2013.00        7.00
75%           .2f    11929.00       24.25       91.70     2018.00       10.00
max           .2f    41977.00       25.78       92.30     2023.00       12.00
std           nan    10753.68        1.19        1.13        6.02        3.45

              Day        Time    Rainfall
count  2121161.00  2121161.00  2121161.00
mean        15.73       10.50        0.79
min          1.00        0.00        0.00
25%          8.00        3.00        0.00
50%         16.00        9.00        0.00
75%         23.00       15.00        0.00
max         31.00       21.00       99.90
std          8.80        6.87        4.29
                            Datetime  StationID   Latitude  Longitude  \
count                        2121161 2121161.00 2121161.00 2121161.00
mean   2013-07-28 07:29:41.846069504   15809.79      23.32      90.46
min              2003-01-01 00:00:00   10120.00      20.87      88.68
25%              2008-05-29 15:00:00   11111.00      22.43      89.37
50%              2013-08-05 12:00:00   11706.00      23.17      90.38
75%              2018-10-12 09:00:00   11929.00      24.25      91.70
max              2023-12-31 21:00:00   41977.00      25.78      92.30
std                              NaN   10753.68       1.19       1.13

            Year      Month        Day       Time   Rainfall
count 2121161.00 2121161.00 2121161.00 2121161.00 2121161.00
mean     2013.07       6.52      15.73      10.50       0.79
min      2003.00       1.00       1.00       0.00       0.00
25%      2008.00       4.00       8.00       3.00       0.00
50%      2013.00       7.00      16.00       9.00       0.00
75%      2018.00      10.00      23.00      15.00       0.00
max      2023.00      12.00      31.00      21.00      99.90
std         6.02       3.45       8.80       6.87       4.29

In [62]:
# Check for impossible negative rainfall
negative_rain = df_rain[df_rain['Rainfall'] < 0]

if not negative_rain.empty:
    print(f"Warning: Found {len(negative_rain)} rows with negative rainfall!")
    print(negative_rain.head())
else:
    print("Passed: No negative rainfall values found.")

Passed: No negative rainfall values found.

In [63]:
df_rain

,Datetime,StationName,StationID,Latitude,Longitude,Year,Month,Day,Time,Rainfall
0,2003-01-01 00:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,0,0.00
1,2003-01-01 03:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,3,0.00
2,2003-01-01 06:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,6,0.00
3,2003-01-01 09:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,9,0.00
4,2003-01-01 12:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,12,0.00
...,...,...,...,...,...,...,...,...,...,...
2121299,2023-12-31 09:00:00,Teknaf,11929,20.87,92.30,2023,12,31,9,0.00
2121300,2023-12-31 12:00:00,Teknaf,11929,20.87,92.30,2023,12,31,12,0.00
2121301,2023-12-31 15:00:00,Teknaf,11929,20.87,92.30,2023,12,31,15,0.00
2121302,2023-12-31 18:00:00,Teknaf,11929,20.87,92.30,2023,12,31,18,0.00
2121303,2023-12-31 21:00:00,Teknaf,11929,20.87,92.30,2023,12,31,21,0.00

In [64]:
# Check for suspicious extreme values
print("Max Rainfall recorded (3-hours):", df_rain['Rainfall'].max())

# Show any rows with > 300mm in 3 hours (adjust threshold if needed)
extreme_rain = df_rain[df_rain['Rainfall'] > 300]
print(f"Number of extreme events (>300mm): {len(extreme_rain)}")
print(extreme_rain)

Max Rainfall recorded (3-hours): 99.9
Number of extreme events (>300mm): 0
Empty DataFrame
Columns: [Datetime, StationName, StationID, Latitude, Longitude, Year, Month, Day, Time, Rainfall]
Index: []

In [65]:
# Check start and end date for each station
station_stats = df_rain.groupby('StationName')['Datetime'].agg(['min', 'max', 'count'])
station_stats['Years'] = (station_stats['max'] - station_stats['min']).dt.days / 365.25

print(station_stats)

                     min                 max  count  Years
StationName
Ambagan(Ctg.) 2003-01-01 2023-12-31 21:00:00  61360  21.00
Barishal      2003-01-01 2023-12-31 21:00:00  61360  21.00
Bhola         2003-01-01 2023-12-31 21:00:00  61360  21.00
Bogura        2003-01-01 2023-12-31 21:00:00  61360  21.00
Chandpur      2003-01-01 2023-12-31 21:00:00  61360  21.00
Chittagong    2008-01-01 2023-12-31 21:00:00  46752  16.00
Chuadanga     2003-01-01 2023-12-31 21:00:00  61360  21.00
Cox'sBazar    2004-01-01 2023-12-31 21:00:00  58440  20.00
Cumilla       2003-01-01 2023-12-31 21:00:00  61360  21.00
Dhaka         2003-01-01 2023-12-31 21:00:00  61360  21.00
Dinajpur      2003-01-01 2023-12-31 21:00:00  61360  21.00
Faridpur      2003-01-01 2023-12-31 21:00:00  61360  21.00
Feni          2003-01-01 2023-01-31 21:00:00  58440  20.08
Hatiya        2003-01-01 2023-10-31 21:00:00  58424  20.83
Ishurdi       2003-01-01 2023-12-31 21:00:00  61360  21.00
Jessore       2003-01-01 2023-12-31 21:00:00  61360  21.00
Khepupara     2003-01-01 2023-12-31 21:00:00  61360  21.00
Khulna        2003-01-01 2023-12-31 21:00:00  61360  21.00
Kutubdia      2003-01-01 2023-12-31 21:00:00  61360  21.00
Madaripur     2003-01-01 2023-12-31 21:00:00  61360  21.00
Maijdee_court 2003-01-01 2023-12-31 21:00:00  61360  21.00
Mongla        2003-01-01 2023-12-31 21:00:00  61360  21.00
Mymensingh    2003-01-01 2023-12-31 21:00:00  61360  21.00
Patuakhali    2003-01-01 2023-12-31 21:00:00  61360  21.00
Rajshahi      2003-01-01 2023-12-31 21:00:00  61360  21.00
Rangamati     2003-01-01 2023-12-31 21:00:00  61360  21.00
Rangpur       2003-01-01 2023-12-31 21:00:00  61360  21.00
Saidpur       2003-01-01 2023-12-31 21:00:00  61360  21.00
Sandwip       2003-01-01 2023-12-31 21:00:00  61360  21.00
Satkhira      2003-01-01 2023-12-31 21:00:00  61225  21.00
Sitakunda     2003-01-01 2023-12-31 21:00:00  61360  21.00
Srimangal     2003-01-01 2023-12-31 21:00:00  58440  21.00
Sylhet        2003-01-01 2023-12-31 21:00:00  61360  21.00
Tangail       2003-01-01 2023-12-31 21:00:00  61360  21.00
Teknaf        2003-01-01 2023-12-31 21:00:00  61360  21.00

In [66]:
df_rain

,Datetime,StationName,StationID,Latitude,Longitude,Year,Month,Day,Time,Rainfall
0,2003-01-01 00:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,0,0.00
1,2003-01-01 03:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,3,0.00
2,2003-01-01 06:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,6,0.00
3,2003-01-01 09:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,9,0.00
4,2003-01-01 12:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,12,0.00
...,...,...,...,...,...,...,...,...,...,...
2121299,2023-12-31 09:00:00,Teknaf,11929,20.87,92.30,2023,12,31,9,0.00
2121300,2023-12-31 12:00:00,Teknaf,11929,20.87,92.30,2023,12,31,12,0.00
2121301,2023-12-31 15:00:00,Teknaf,11929,20.87,92.30,2023,12,31,15,0.00
2121302,2023-12-31 18:00:00,Teknaf,11929,20.87,92.30,2023,12,31,18,0.00
2121303,2023-12-31 21:00:00,Teknaf,11929,20.87,92.30,2023,12,31,21,0.00

In [67]:
zero_count = (df_rain['Rainfall'] == 0).sum()
total_count = len(df_rain)
zero_percent = (zero_count / total_count) * 100

print(f"Percentage of time with NO Rain: {zero_percent:.2f}%")

Percentage of time with NO Rain: 89.05%

In [68]:
# Check if there are multiple entries for the same Station + Time
conflicts = df_rain[df_rain.duplicated(subset=['StationName', 'Datetime'], keep=False)]

if not conflicts.empty:
    print(f"Warning: Found {len(conflicts)} conflicting time slots!")
    print(conflicts.head())
else:
    print("Passed: No conflicting time slots found.")

Warning: Found 210 conflicting time slots!
                   Datetime StationName  StationID  Latitude  Longitude  Year  \
1806944 2020-07-01 00:00:00    Satkhira      11610     22.72      89.08  2020
1806945 2020-07-01 00:00:00    Satkhira      11610     22.72      89.08  2020
1806954 2020-07-01 15:00:00    Satkhira      11610     22.72      89.08  2020
1806955 2020-07-01 15:00:00    Satkhira      11610     22.72      89.08  2020
1806968 2020-07-02 12:00:00    Satkhira      11610     22.72      89.08  2020

         Month  Day  Time  Rainfall
1806944      7    1     0     24.00
1806945      7    1     0      0.00
1806954      7    1    15      1.00
1806955      7    1    15      0.00
1806968      7    2    12     20.00

In [69]:
df_rain

,Datetime,StationName,StationID,Latitude,Longitude,Year,Month,Day,Time,Rainfall
0,2003-01-01 00:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,0,0.00
1,2003-01-01 03:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,3,0.00
2,2003-01-01 06:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,6,0.00
3,2003-01-01 09:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,9,0.00
4,2003-01-01 12:00:00,Ambagan(Ctg.),41977,22.35,91.82,2003,1,1,12,0.00
...,...,...,...,...,...,...,...,...,...,...
2121299,2023-12-31 09:00:00,Teknaf,11929,20.87,92.30,2023,12,31,9,0.00
2121300,2023-12-31 12:00:00,Teknaf,11929,20.87,92.30,2023,12,31,12,0.00
2121301,2023-12-31 15:00:00,Teknaf,11929,20.87,92.30,2023,12,31,15,0.00
2121302,2023-12-31 18:00:00,Teknaf,11929,20.87,92.30,2023,12,31,18,0.00
2121303,2023-12-31 21:00:00,Teknaf,11929,20.87,92.30,2023,12,31,21,0.00

In [70]:
# Overwrite df_rain with the fixed version
df_rain = df_rain.groupby(
    ['StationName', 'Datetime', 'StationID', 'Latitude', 'Longitude','Year',	'Month',	'Day',	'Time'],
    as_index=False
)['Rainfall'].max()

print(f"Update complete. Current row count: {len(df_rain)}")

Update complete. Current row count: 2121056

In [71]:
df_rain

,StationName,Datetime,StationID,Latitude,Longitude,Year,Month,Day,Time,Rainfall
0,Ambagan(Ctg.),2003-01-01 00:00:00,41977,22.35,91.82,2003,1,1,0,0.00
1,Ambagan(Ctg.),2003-01-01 03:00:00,41977,22.35,91.82,2003,1,1,3,0.00
2,Ambagan(Ctg.),2003-01-01 06:00:00,41977,22.35,91.82,2003,1,1,6,0.00
3,Ambagan(Ctg.),2003-01-01 09:00:00,41977,22.35,91.82,2003,1,1,9,0.00
4,Ambagan(Ctg.),2003-01-01 12:00:00,41977,22.35,91.82,2003,1,1,12,0.00
...,...,...,...,...,...,...,...,...,...,...
2121051,Teknaf,2023-12-31 09:00:00,11929,20.87,92.30,2023,12,31,9,0.00
2121052,Teknaf,2023-12-31 12:00:00,11929,20.87,92.30,2023,12,31,12,0.00
2121053,Teknaf,2023-12-31 15:00:00,11929,20.87,92.30,2023,12,31,15,0.00
2121054,Teknaf,2023-12-31 18:00:00,11929,20.87,92.30,2023,12,31,18,0.00
2121055,Teknaf,2023-12-31 21:00:00,11929,20.87,92.30,2023,12,31,21,0.00

In [72]:
# Check if there are multiple entries for the same Station + Time
conflicts = df_rain[df_rain.duplicated(subset=['StationName', 'Datetime'], keep=False)]

if not conflicts.empty:
    print(f"Warning: Found {len(conflicts)} conflicting time slots!")
    print(conflicts.head())
else:
    print("Passed: No conflicting time slots found.")

Passed: No conflicting time slots found.

In [73]:
# Function to check gaps for a single station
def check_gaps(group):
    # Create the ideal full range of 3-hourly timestamps for this station
    full_range = pd.date_range(start=group['Datetime'].min(),
                               end=group['Datetime'].max(),
                               freq='3H')

    # Compare actual data length to ideal length
    missing_count = len(full_range) - len(group)
    return missing_count

# Apply to all stations
gaps = df_rain.groupby('StationName').apply(check_gaps)

print("Missing 3-hour slots per station:")
print(gaps[gaps > 0]) # Only show stations with gaps

Missing 3-hour slots per station:
StationName
Feni          248
Hatiya       2448
Satkhira      240
Srimangal    2920
dtype: int64

/tmp/ipython-input-1671359142.py:4: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  full_range = pd.date_range(start=group['Datetime'].min(),
/tmp/ipython-input-1671359142.py:13: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  gaps = df_rain.groupby('StationName').apply(check_gaps)

## **Merging humidity, dew point, pressure, speed and direction data**

In [74]:
file_path = '/content/drive/MyDrive/Dry Thunderstrom/Data/3-Hourly Dew Point Temperature.csv'
df_dew = pd.read_csv(file_path)

In [75]:
df_dew

,Datetime,StationName,StationID,Latitude,Longitude,Year,Month,Day,Time,DewPointTemperature
0,1980-01-01 00:00:00,Dhaka,11111,23.77,90.38,1980,1,1,0,10.00
1,1980-01-01 03:00:00,Dhaka,11111,23.77,90.38,1980,1,1,3,15.00
2,1980-01-01 06:00:00,Dhaka,11111,23.77,90.38,1980,1,1,6,12.00
3,1980-01-01 09:00:00,Dhaka,11111,23.77,90.38,1980,1,1,9,10.00
4,1980-01-01 12:00:00,Dhaka,11111,23.77,90.38,1980,1,1,12,12.00
...,...,...,...,...,...,...,...,...,...,...
4181102,2023-12-31 09:00:00,Ambangan(Ctg.),41977,22.35,91.82,2023,12,31,9,19.00
4181103,2023-12-31 12:00:00,Ambangan(Ctg.),41977,22.35,91.82,2023,12,31,12,19.00
4181104,2023-12-31 15:00:00,Ambangan(Ctg.),41977,22.35,91.82,2023,12,31,15,18.00
4181105,2023-12-31 18:00:00,Ambangan(Ctg.),41977,22.35,91.82,2023,12,31,18,19.00
4181106,2023-12-31 21:00:00,Ambangan(Ctg.),41977,22.35,91.82,2023,12,31,21,18.00

In [76]:
df_dew

,Datetime,StationName,StationID,Latitude,Longitude,Year,Month,Day,Time,DewPointTemperature
0,1980-01-01 00:00:00,Dhaka,11111,23.77,90.38,1980,1,1,0,10.00
1,1980-01-01 03:00:00,Dhaka,11111,23.77,90.38,1980,1,1,3,15.00
2,1980-01-01 06:00:00,Dhaka,11111,23.77,90.38,1980,1,1,6,12.00
3,1980-01-01 09:00:00,Dhaka,11111,23.77,90.38,1980,1,1,9,10.00
4,1980-01-01 12:00:00,Dhaka,11111,23.77,90.38,1980,1,1,12,12.00
...,...,...,...,...,...,...,...,...,...,...
4181102,2023-12-31 09:00:00,Ambangan(Ctg.),41977,22.35,91.82,2023,12,31,9,19.00
4181103,2023-12-31 12:00:00,Ambangan(Ctg.),41977,22.35,91.82,2023,12,31,12,19.00
4181104,2023-12-31 15:00:00,Ambangan(Ctg.),41977,22.35,91.82,2023,12,31,15,18.00
4181105,2023-12-31 18:00:00,Ambangan(Ctg.),41977,22.35,91.82,2023,12,31,18,19.00
4181106,2023-12-31 21:00:00,Ambangan(Ctg.),41977,22.35,91.82,2023,12,31,21,18.00

In [77]:
station_coords_df = (
    df_dew
    [['StationID', 'StationName', 'Latitude', 'Longitude']]
    .drop_duplicates()
    .sort_values('StationID')
    .reset_index(drop=True)
)

station_coords_df

    StationID     StationName  Latitude  Longitude
0       10120        Dinajpur     25.65      88.68
1       10208         Rangpur     25.73      89.23
2       10320        Rajshahi     24.37      88.70
3       10408          Bogura     24.85      89.37
4       10609      Mymensingh     24.72      90.43
5       10705          Sylhet     24.90      91.88
6       10724       Srimangal     24.30      91.73
7       10910         Ishurdi     24.13      89.05
8       11111           Dhaka     23.77      90.38
9       11313         Cumilla     23.43      91.18
10      11316        Chandpur     23.27      90.70
11      11407         Jessore     23.18      89.17
12      11505        Faridpur     23.60      89.85
13      11513       Madaripur     23.17      90.18
14      11604          Khulna     22.78      89.53
15      11610        Satkhira     22.72      89.08
16      11704        Barishal     22.75      90.33
17      11706           Bhola     22.68      90.65
18      11805            Feni     23.03      91.42
19      11809   Maijdee_court     22.87      91.10
20      11814          Hatiya     22.43      91.10
21      11912       Sitakunda     23.58      91.70
22      11916         Sandwip     22.48      91.43
23      11921      Chittagong     22.27      91.82
24      11925        Kutubdia     21.82      91.85
25      11927      Cox'sBazar     21.43      91.93
26      11929          Teknaf     20.87      92.30
27      12007       Rangamati     22.53      92.20
28      12103      Patuakhali     22.33      90.33
29      12110       Khepupara     21.98      90.23
30      41858         Saidpur     25.78      88.88
31      41909         Tangail     24.25      89.92
32      41926       Chuadanga     23.65      88.87
33      41958          Mongla     22.33      89.60
34      41977  Ambangan(Ctg.)     22.35      91.82

In [78]:
# Example values
station_id = 11912
new_lat = 22.62
new_lon = 91.67

df_rain.loc[df_rain["StationID"] == station_id, ["Latitude", "Longitude"]] = [new_lat, new_lon]

In [79]:
df_rain.loc[df_rain["StationID"] == 11912,
            ["StationID", "StationName", "Latitude", "Longitude"]
           ].drop_duplicates()

         StationID StationName  Latitude  Longitude
1817176      11912   Sitakunda     22.62      91.67

In [80]:
# Select only necessary columns from df_dew
df_dew_small = df_dew[
    ['StationID', 'Year', 'Month', 'Day', 'Time', 'DewPointTemperature']
]

# Left merge: keeps df exactly as it is
df_rain = df_rain.merge(
    df_dew_small,
    on=['StationID', 'Year', 'Month', 'Day', 'Time'],
    how='left'
)

In [81]:
df_rain

,StationName,Datetime,StationID,Latitude,Longitude,Year,Month,Day,Time,Rainfall,DewPointTemperature
0,Ambagan(Ctg.),2003-01-01 00:00:00,41977,22.35,91.82,2003,1,1,0,0.00,12.00
1,Ambagan(Ctg.),2003-01-01 03:00:00,41977,22.35,91.82,2003,1,1,3,0.00,13.00
2,Ambagan(Ctg.),2003-01-01 06:00:00,41977,22.35,91.82,2003,1,1,6,0.00,15.00
3,Ambagan(Ctg.),2003-01-01 09:00:00,41977,22.35,91.82,2003,1,1,9,0.00,9.00
4,Ambagan(Ctg.),2003-01-01 12:00:00,41977,22.35,91.82,2003,1,1,12,0.00,13.00
...,...,...,...,...,...,...,...,...,...,...,...
2121054,Teknaf,2023-12-31 09:00:00,11929,20.87,92.30,2023,12,31,9,0.00,14.00
2121055,Teknaf,2023-12-31 12:00:00,11929,20.87,92.30,2023,12,31,12,0.00,15.70
2121056,Teknaf,2023-12-31 15:00:00,11929,20.87,92.30,2023,12,31,15,0.00,15.60
2121057,Teknaf,2023-12-31 18:00:00,11929,20.87,92.30,2023,12,31,18,0.00,14.80
2121058,Teknaf,2023-12-31 21:00:00,11929,20.87,92.30,2023,12,31,21,0.00,15.00

In [82]:
# --- STEP 1: Identification ---
# Define the unique key for your data
unique_cols = ['StationID', 'Year', 'Month', 'Day', 'Time']

# Check how many duplicates exist based on this key
dup_mask = df_rain.duplicated(subset=unique_cols, keep=False)
num_dups = dup_mask.sum()

print(f"Found {num_dups} duplicate rows (including originals).")

# Optional: View the conflicting rows to see if DewPoint varies
if num_dups > 0:
    print("\nSample of duplicate rows:")
    print(df_rain[dup_mask].sort_values(by=unique_cols).head(10))

# --- STEP 2: Removal ---
# We keep the 'first' occurrence and drop the others.
# This brings your count back down to exactly 2,121,056
df_rain = df_rain.drop_duplicates(subset=unique_cols, keep='first')

print(f"\nDuplicates removed. Final Row Count: {len(df_rain)}")

Found 6 duplicate rows (including originals).

Sample of duplicate rows:
        StationName            Datetime  StationID  Latitude  Longitude  Year  \
1186492   Madaripur 2018-01-26 12:00:00      11513     23.17      90.18  2018
1186493   Madaripur 2018-01-26 12:00:00      11513     23.17      90.18  2018
1186517   Madaripur 2018-01-29 12:00:00      11513     23.17      90.18  2018
1186518   Madaripur 2018-01-29 12:00:00      11513     23.17      90.18  2018
1186534   Madaripur 2018-01-31 12:00:00      11513     23.17      90.18  2018
1186535   Madaripur 2018-01-31 12:00:00      11513     23.17      90.18  2018

         Month  Day  Time  Rainfall  DewPointTemperature
1186492      1   26    12      0.00                17.00
1186493      1   26    12      0.00                14.00
1186517      1   29    12      0.00                17.00
1186518      1   29    12      0.00                14.00
1186534      1   31    12      0.00                17.00
1186535      1   31    12      0.00                14.00

Duplicates removed. Final Row Count: 2121056

In [83]:
df_rain.describe()

,Datetime,StationID,Latitude,Longitude,Year,Month,Day,Time,Rainfall,DewPointTemperature
count,2121056,2121056.00,2121056.00,2121056.00,2121056.00,2121056.00,2121056.00,2121056.00,2121056.00,2112040.00
mean,2013-07-28 04:28:15.393989120,15810.00,23.30,90.46,2013.07,6.52,15.73,10.50,0.79,21.61
min,2003-01-01 00:00:00,10120.00,20.87,88.68,2003.00,1.00,1.00,0.00,0.00,0.10
25%,2008-05-29 12:00:00,11111.00,22.43,89.37,2008.00,4.00,8.00,5.25,0.00,18.00
50%,2013-08-05 06:00:00,11706.00,23.03,90.38,2013.00,7.00,16.00,10.50,0.00,24.00
75%,2018-10-12 03:00:00,11929.00,24.25,91.67,2018.00,10.00,23.00,15.75,0.00,26.00
max,2023-12-31 21:00:00,41977.00,25.78,92.30,2023.00,12.00,31.00,21.00,99.90,36.00
std,NaN,10753.90,1.20,1.13,6.02,3.45,8.80,6.87,4.29,5.18

In [84]:
df_rain.isna()

,StationName,Datetime,StationID,Latitude,Longitude,Year,Month,Day,Time,Rainfall,DewPointTemperature
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
2121054,False,False,False,False,False,False,False,False,False,False,False
2121055,False,False,False,False,False,False,False,False,False,False,False
2121056,False,False,False,False,False,False,False,False,False,False,False
2121057,False,False,False,False,False,False,False,False,False,False,False
2121058,False,False,False,False,False,False,False,False,False,False,False

In [85]:
# 1. Check the count of missing values per column
print("Missing Values per Column:")
print(df_rain.isna().sum())

# 2. (Optional) See the percentage of missing data
print("\nPercentage of Missing Data:")
print(df_rain.isna().mean() * 100)

Missing Values per Column:
StationName               0
Datetime                  0
StationID                 0
Latitude                  0
Longitude                 0
Year                      0
Month                     0
Day                       0
Time                      0
Rainfall                  0
DewPointTemperature    9016
dtype: int64

Percentage of Missing Data:
StationName           0.00
Datetime              0.00
StationID             0.00
Latitude              0.00
Longitude             0.00
Year                  0.00
Month                 0.00
Day                   0.00
Time                  0.00
Rainfall              0.00
DewPointTemperature   0.43
dtype: float64

In [86]:
# Interpolate missing Dewpoint values within each station
# We use 'transform' to keep the dataframe shape identical
df_rain['DewPointTemperature'] = df_rain.groupby('StationID')['DewPointTemperature'].transform(
    lambda x: x.interpolate(method='linear', limit_direction='both')
)

# Verify that 9016 NaNs are now 0
print(f"Remaining Missing Dewpoint: {df_rain['DewPointTemperature'].isna().sum()}")

Remaining Missing Dewpoint: 0

/tmp/ipython-input-3232410263.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rain['DewPointTemperature'] = df_rain.groupby('StationID')['DewPointTemperature'].transform(

In [87]:
file_path = '/content/drive/MyDrive/Dry Thunderstrom/Data/3-Hourly Humidity.csv'
df_hum = pd.read_csv(file_path)

In [88]:
df_hum

,Datetime,StationName,StationID,Latitude,Longitude,Year,Month,Day,Time,Humidity
0,1980-01-01 00:00:00,Dhaka,11111,23.77,90.38,1980,1,1,0,90.00
1,1980-01-01 03:00:00,Dhaka,11111,23.77,90.38,1980,1,1,3,84.00
2,1980-01-01 06:00:00,Dhaka,11111,23.77,90.38,1980,1,1,6,49.00
3,1980-01-01 09:00:00,Dhaka,11111,23.77,90.38,1980,1,1,9,44.00
4,1980-01-01 12:00:00,Dhaka,11111,23.77,90.38,1980,1,1,12,61.00
...,...,...,...,...,...,...,...,...,...,...
4295307,2023-12-31 09:00:00,Sitakunda,11912,23.58,91.70,2023,12,31,9,28.00
4295308,2023-12-31 12:00:00,Sitakunda,11912,23.58,91.70,2023,12,31,12,71.00
4295309,2023-12-31 15:00:00,Sitakunda,11912,23.58,91.70,2023,12,31,15,72.00
4295310,2023-12-31 18:00:00,Sitakunda,11912,23.58,91.70,2023,12,31,18,74.00
4295311,2023-12-31 21:00:00,Sitakunda,11912,23.58,91.70,2023,12,31,21,78.00

In [89]:
df_hum_small = df_hum[
    ['StationID', 'Year', 'Month', 'Day', 'Time', 'Humidity']
]

In [90]:
df_rain = df_rain.merge(
    df_hum_small,
    on=['StationID', 'Year', 'Month', 'Day', 'Time'],
    how='left'
)

In [91]:
df_rain

,StationName,Datetime,StationID,Latitude,Longitude,Year,Month,Day,Time,Rainfall,DewPointTemperature,Humidity
0,Ambagan(Ctg.),2003-01-01 00:00:00,41977,22.35,91.82,2003,1,1,0,0.00,12.00,91.00
1,Ambagan(Ctg.),2003-01-01 03:00:00,41977,22.35,91.82,2003,1,1,3,0.00,13.00,74.00
2,Ambagan(Ctg.),2003-01-01 06:00:00,41977,22.35,91.82,2003,1,1,6,0.00,15.00,57.00
3,Ambagan(Ctg.),2003-01-01 09:00:00,41977,22.35,91.82,2003,1,1,9,0.00,9.00,35.00
4,Ambagan(Ctg.),2003-01-01 12:00:00,41977,22.35,91.82,2003,1,1,12,0.00,13.00,61.00
...,...,...,...,...,...,...,...,...,...,...,...,...
2121051,Teknaf,2023-12-31 09:00:00,11929,20.87,92.30,2023,12,31,9,0.00,14.00,50.20
2121052,Teknaf,2023-12-31 12:00:00,11929,20.87,92.30,2023,12,31,12,0.00,15.70,71.50
2121053,Teknaf,2023-12-31 15:00:00,11929,20.87,92.30,2023,12,31,15,0.00,15.60,78.40
2121054,Teknaf,2023-12-31 18:00:00,11929,20.87,92.30,2023,12,31,18,0.00,14.80,84.20
2121055,Teknaf,2023-12-31 21:00:00,11929,20.87,92.30,2023,12,31,21,0.00,15.00,88.90

In [92]:
# 1. Check the count of missing values per column
print("Missing Values per Column:")
print(df_rain.isna().sum())

# 2. (Optional) See the percentage of missing data
print("\nPercentage of Missing Data:")
print(df_rain.isna().mean() * 100)

Missing Values per Column:
StationName               0
Datetime                  0
StationID                 0
Latitude                  0
Longitude                 0
Year                      0
Month                     0
Day                       0
Time                      0
Rainfall                  0
DewPointTemperature       0
Humidity               2920
dtype: int64

Percentage of Missing Data:
StationName           0.00
Datetime              0.00
StationID             0.00
Latitude              0.00
Longitude             0.00
Year                  0.00
Month                 0.00
Day                   0.00
Time                  0.00
Rainfall              0.00
DewPointTemperature   0.00
Humidity              0.14
dtype: float64

In [93]:
# 1. Decouple to avoid warnings (Safety Step)
df_rain = df_rain.copy()

# 2. Interpolate missing Humidity values within each station
# We group by StationID so we don't accidentally interpolate between different cities
df_rain['Humidity'] = df_rain.groupby('StationID')['Humidity'].transform(
    lambda x: x.interpolate(method='linear', limit_direction='both')
)

# 3. Verify that 2920 NaNs are now 0
print(f"Remaining Missing Humidity: {df_rain['Humidity'].isna().sum()}")

Remaining Missing Humidity: 0

In [94]:
file_path = '/content/drive/MyDrive/Dry Thunderstrom/Data/3-Hourly Station Level Pressure.csv'
df_pressure = pd.read_csv(file_path)
df_pressure

,Datetime,StationName,StationID,Latitude,Longitude,Year,Month,Day,Time,StationLevelPressure
0,1980-01-01 00:00:00,Dhaka,11111,23.77,90.38,1980,1,1,0,1011.70
1,1980-01-01 03:00:00,Dhaka,11111,23.77,90.38,1980,1,1,3,1014.80
2,1980-01-01 06:00:00,Dhaka,11111,23.77,90.38,1980,1,1,6,1013.40
3,1980-01-01 09:00:00,Dhaka,11111,23.77,90.38,1980,1,1,9,1011.20
4,1980-01-01 12:00:00,Dhaka,11111,23.77,90.38,1980,1,1,12,1011.40
...,...,...,...,...,...,...,...,...,...,...
4227786,2022-12-31 09:00:00,Teknaf,11929,20.87,92.30,2022,12,31,9,1014.70
4227787,2022-12-31 12:00:00,Teknaf,11929,20.87,92.30,2022,12,31,12,1014.90
4227788,2022-12-31 15:00:00,Teknaf,11929,20.87,92.30,2022,12,31,15,1016.50
4227789,2022-12-31 18:00:00,Teknaf,11929,20.87,92.30,2022,12,31,18,1016.40
4227790,2022-12-31 21:00:00,Teknaf,11929,20.87,92.30,2022,12,31,21,1016.00

In [95]:
df_pressure_small = df_pressure[
    ['StationID', 'Year', 'Month', 'Day', 'Time', 'StationLevelPressure']
]

In [96]:
df_rain = df_rain.merge(
    df_pressure_small,
    on=['StationID', 'Year', 'Month', 'Day', 'Time'],
    how='left'
)
df_rain

,StationName,Datetime,StationID,Latitude,Longitude,Year,Month,Day,Time,Rainfall,DewPointTemperature,Humidity,StationLevelPressure
0,Ambagan(Ctg.),2003-01-01 00:00:00,41977,22.35,91.82,2003,1,1,0,0.00,12.00,91.00,1009.70
1,Ambagan(Ctg.),2003-01-01 03:00:00,41977,22.35,91.82,2003,1,1,3,0.00,13.00,74.00,1011.30
2,Ambagan(Ctg.),2003-01-01 06:00:00,41977,22.35,91.82,2003,1,1,6,0.00,15.00,57.00,1011.20
3,Ambagan(Ctg.),2003-01-01 09:00:00,41977,22.35,91.82,2003,1,1,9,0.00,9.00,35.00,1010.30
4,Ambagan(Ctg.),2003-01-01 12:00:00,41977,22.35,91.82,2003,1,1,12,0.00,13.00,61.00,1010.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121051,Teknaf,2023-12-31 09:00:00,11929,20.87,92.30,2023,12,31,9,0.00,14.00,50.20,NaN
2121052,Teknaf,2023-12-31 12:00:00,11929,20.87,92.30,2023,12,31,12,0.00,15.70,71.50,NaN
2121053,Teknaf,2023-12-31 15:00:00,11929,20.87,92.30,2023,12,31,15,0.00,15.60,78.40,NaN
2121054,Teknaf,2023-12-31 18:00:00,11929,20.87,92.30,2023,12,31,18,0.00,14.80,84.20,NaN
2121055,Teknaf,2023-12-31 21:00:00,11929,20.87,92.30,2023,12,31,21,0.00,15.00,88.90,NaN

In [97]:
# 1. Check the count of missing values per column
print("Missing Values per Column:")
print(df_rain.isna().sum())

# 2. (Optional) See the percentage of missing data
print("\nPercentage of Missing Data:")
print(df_rain.isna().mean() * 100)

Missing Values per Column:
StationName                0
Datetime                   0
StationID                  0
Latitude                   0
Longitude                  0
Year                       0
Month                      0
Day                        0
Time                       0
Rainfall                   0
DewPointTemperature        0
Humidity                   0
StationLevelPressure    5840
dtype: int64

Percentage of Missing Data:
StationName            0.00
Datetime               0.00
StationID              0.00
Latitude               0.00
Longitude              0.00
Year                   0.00
Month                  0.00
Day                    0.00
Time                   0.00
Rainfall               0.00
DewPointTemperature    0.00
Humidity               0.00
StationLevelPressure   0.28
dtype: float64

In [98]:
# 1. Decouple to avoid warnings
df_rain = df_rain.copy()

# 2. Interpolate missing Pressure values within each station
df_rain['StationLevelPressure'] = df_rain.groupby('StationID')['StationLevelPressure'].transform(
    lambda x: x.interpolate(method='linear', limit_direction='both')
)

# 3. Verify
print(f"Remaining Missing Pressure: {df_rain['StationLevelPressure'].isna().sum()}")

Remaining Missing Pressure: 0

In [99]:
df_rain

,StationName,Datetime,StationID,Latitude,Longitude,Year,Month,Day,Time,Rainfall,DewPointTemperature,Humidity,StationLevelPressure
0,Ambagan(Ctg.),2003-01-01 00:00:00,41977,22.35,91.82,2003,1,1,0,0.00,12.00,91.00,1009.70
1,Ambagan(Ctg.),2003-01-01 03:00:00,41977,22.35,91.82,2003,1,1,3,0.00,13.00,74.00,1011.30
2,Ambagan(Ctg.),2003-01-01 06:00:00,41977,22.35,91.82,2003,1,1,6,0.00,15.00,57.00,1011.20
3,Ambagan(Ctg.),2003-01-01 09:00:00,41977,22.35,91.82,2003,1,1,9,0.00,9.00,35.00,1010.30
4,Ambagan(Ctg.),2003-01-01 12:00:00,41977,22.35,91.82,2003,1,1,12,0.00,13.00,61.00,1010.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121051,Teknaf,2023-12-31 09:00:00,11929,20.87,92.30,2023,12,31,9,0.00,14.00,50.20,1016.00
2121052,Teknaf,2023-12-31 12:00:00,11929,20.87,92.30,2023,12,31,12,0.00,15.70,71.50,1016.00
2121053,Teknaf,2023-12-31 15:00:00,11929,20.87,92.30,2023,12,31,15,0.00,15.60,78.40,1016.00
2121054,Teknaf,2023-12-31 18:00:00,11929,20.87,92.30,2023,12,31,18,0.00,14.80,84.20,1016.00
2121055,Teknaf,2023-12-31 21:00:00,11929,20.87,92.30,2023,12,31,21,0.00,15.00,88.90,1016.00

In [100]:
file_path = '/content/drive/MyDrive/Rainfall/Data/Processed_wind_speed_direction_data.csv'
df_wind = pd.read_csv(file_path)
df_wind

,Datetime,StationName,StationID,Latitude,Longitude,Year,Month,Day,Time,SP,DR
0,1981-01-01 00:00:00,Dinajpur,10120,25.65,88.68,1981,1,1,0,0.00,0.00
1,1981-01-01 03:00:00,Dinajpur,10120,25.65,88.68,1981,1,1,3,5.00,31.00
2,1981-01-01 06:00:00,Dinajpur,10120,25.65,88.68,1981,1,1,6,6.00,31.00
3,1981-01-01 09:00:00,Dinajpur,10120,25.65,88.68,1981,1,1,9,5.00,31.00
4,1981-01-01 12:00:00,Dinajpur,10120,25.65,88.68,1981,1,1,12,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...
4290351,2023-12-31 09:00:00,Ambagan(Ctg.),41977,22.35,91.82,2023,12,31,9,0.00,0.00
4290352,2023-12-31 12:00:00,Ambagan(Ctg.),41977,22.35,91.82,2023,12,31,12,0.00,0.00
4290353,2023-12-31 15:00:00,Ambagan(Ctg.),41977,22.35,91.82,2023,12,31,15,0.00,0.00
4290354,2023-12-31 18:00:00,Ambagan(Ctg.),41977,22.35,91.82,2023,12,31,18,0.00,0.00
4290355,2023-12-31 21:00:00,Ambagan(Ctg.),41977,22.35,91.82,2023,12,31,21,0.00,0.00

In [101]:
df_wind_small = df_wind[
    ['StationID', 'Year', 'Month', 'Day', 'Time', 'SP', 'DR']
]

In [102]:
df_wind_small

         StationID  Year  Month  Day  Time   SP    DR
0            10120  1981      1    1     0 0.00  0.00
1            10120  1981      1    1     3 5.00 31.00
2            10120  1981      1    1     6 6.00 31.00
3            10120  1981      1    1     9 5.00 31.00
4            10120  1981      1    1    12 0.00  0.00
...            ...   ...    ...  ...   ...  ...   ...
4290351      41977  2023     12   31     9 0.00  0.00
4290352      41977  2023     12   31    12 0.00  0.00
4290353      41977  2023     12   31    15 0.00  0.00
4290354      41977  2023     12   31    18 0.00  0.00
4290355      41977  2023     12   31    21 0.00  0.00

[4290356 rows x 7 columns]

In [103]:
df_rain = df_rain.merge(
    df_wind_small,
    on=['StationID', 'Year', 'Month', 'Day', 'Time'],
    how='left'
)
df_rain

,StationName,Datetime,StationID,Latitude,Longitude,Year,Month,Day,Time,Rainfall,DewPointTemperature,Humidity,StationLevelPressure,SP,DR
0,Ambagan(Ctg.),2003-01-01 00:00:00,41977,22.35,91.82,2003,1,1,0,0.00,12.00,91.00,1009.70,0.00,0.00
1,Ambagan(Ctg.),2003-01-01 03:00:00,41977,22.35,91.82,2003,1,1,3,0.00,13.00,74.00,1011.30,0.00,0.00
2,Ambagan(Ctg.),2003-01-01 06:00:00,41977,22.35,91.82,2003,1,1,6,0.00,15.00,57.00,1011.20,4.00,31.00
3,Ambagan(Ctg.),2003-01-01 09:00:00,41977,22.35,91.82,2003,1,1,9,0.00,9.00,35.00,1010.30,2.00,5.00
4,Ambagan(Ctg.),2003-01-01 12:00:00,41977,22.35,91.82,2003,1,1,12,0.00,13.00,61.00,1010.40,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121051,Teknaf,2023-12-31 09:00:00,11929,20.87,92.30,2023,12,31,9,0.00,14.00,50.20,1016.00,NaN,NaN
2121052,Teknaf,2023-12-31 12:00:00,11929,20.87,92.30,2023,12,31,12,0.00,15.70,71.50,1016.00,NaN,NaN
2121053,Teknaf,2023-12-31 15:00:00,11929,20.87,92.30,2023,12,31,15,0.00,15.60,78.40,1016.00,NaN,NaN
2121054,Teknaf,2023-12-31 18:00:00,11929,20.87,92.30,2023,12,31,18,0.00,14.80,84.20,1016.00,NaN,NaN
2121055,Teknaf,2023-12-31 21:00:00,11929,20.87,92.30,2023,12,31,21,0.00,15.00,88.90,1016.00,NaN,NaN

In [104]:
df_rain.isna().sum()

StationName                0
Datetime                   0
StationID                  0
Latitude                   0
Longitude                  0
Year                       0
Month                      0
Day                        0
Time                       0
Rainfall                   0
DewPointTemperature        0
Humidity                   0
StationLevelPressure       0
SP                      4437
DR                      4437
dtype: int64

In [105]:
import pandas as pd

# 1. Group by StationID and count missing 'Rainfall' values
station_missing = df_rain.groupby('StationID')['SP'].apply(lambda x: x.isna().sum())
station_total = df_rain.groupby('StationID')['SP'].size()

# 2. Create a Summary DataFrame
report = pd.DataFrame({
    'StationName': df_rain.groupby('StationID')['StationName'].first(), # Grab the name
    'Total_Rows': station_total,
    'Missing_Rows': station_missing,
    'Missing_Pct': (station_missing / station_total * 100).round(2)
})

# 3. Sort by percentage to see the worst stations first
report = report.sort_values(by='Missing_Pct', ascending=False)

# 4. Show stations that actually have missing data
print("--- Stations with Missing SP Data ---")
print(report[report['Missing_Rows'] > 0])

# Optional: View the full list
# print(report)

--- Stations with Missing SP Data ---
          StationName  Total_Rows  Missing_Rows  Missing_Pct
StationID
11916         Sandwip       61360          2920         4.76
11929          Teknaf       61360          1224         1.99
11704        Barishal       61360           177         0.29
11407         Jessore       61360           116         0.19

In [106]:
# Filter for Sandwip (ID 11916) AND Missing Wind Speed
sandwip_missing = df_rain[
    (df_rain['StationID'] == 11916) &
    (df_rain['SP'].isna())
]

print(f"Total Missing Rows for Sandwip: {len(sandwip_missing)}")

# Show the dates where data is missing
print("\n--- Sample Dates with Missing Data ---")
print(sandwip_missing[['Datetime', 'Year', 'Month', 'Day', 'Time']].head(30))

# Optional: Check if it's a specific block of time (e.g., a whole year)
print("\n--- Years with Missing Data ---")
print(sandwip_missing['Year'].value_counts().sort_index())

Total Missing Rows for Sandwip: 2920

--- Sample Dates with Missing Data ---
                   Datetime  Year  Month  Day  Time
1694696 2003-01-01 00:00:00  2003      1    1     0
1694697 2003-01-01 03:00:00  2003      1    1     3
1694698 2003-01-01 06:00:00  2003      1    1     6
1694699 2003-01-01 09:00:00  2003      1    1     9
1694700 2003-01-01 12:00:00  2003      1    1    12
1694701 2003-01-01 15:00:00  2003      1    1    15
1694702 2003-01-01 18:00:00  2003      1    1    18
1694703 2003-01-01 21:00:00  2003      1    1    21
1694704 2003-01-02 00:00:00  2003      1    2     0
1694705 2003-01-02 03:00:00  2003      1    2     3
1694706 2003-01-02 06:00:00  2003      1    2     6
1694707 2003-01-02 09:00:00  2003      1    2     9
1694708 2003-01-02 12:00:00  2003      1    2    12
1694709 2003-01-02 15:00:00  2003      1    2    15
1694710 2003-01-02 18:00:00  2003      1    2    18
1694711 2003-01-02 21:00:00  2003      1    2    21
1694712 2003-01-03 00:00:00  2003      1    3     0
1694713 2003-01-03 03:00:00  2003      1    3     3
1694714 2003-01-03 06:00:00  2003      1    3     6
1694715 2003-01-03 09:00:00  2003      1    3     9
1694716 2003-01-03 12:00:00  2003      1    3    12
1694717 2003-01-03 15:00:00  2003      1    3    15
1694718 2003-01-03 18:00:00  2003      1    3    18
1694719 2003-01-03 21:00:00  2003      1    3    21
1694720 2003-01-04 00:00:00  2003      1    4     0
1694721 2003-01-04 03:00:00  2003      1    4     3
1694722 2003-01-04 06:00:00  2003      1    4     6
1694723 2003-01-04 09:00:00  2003      1    4     9
1694724 2003-01-04 12:00:00  2003      1    4    12
1694725 2003-01-04 15:00:00  2003      1    4    15

--- Years with Missing Data ---
Year
2003    2920
Name: count, dtype: int64

In [107]:
# Filter for Teknaf (ID 61360) AND Missing Wind Speed
sandwip_missing = df_rain[
    (df_rain['StationID'] == 11929) &
    (df_rain['SP'].isna())
]

print(f"Total Missing Rows for Sandwip: {len(sandwip_missing)}")

# Show the dates where data is missing
print("\n--- Sample Dates with Missing Data ---")
print(sandwip_missing[['Datetime', 'Year', 'Month', 'Day', 'Time']].head(30))

# Optional: Check if it's a specific block of time (e.g., a whole year)
print("\n--- Years with Missing Data ---")
print(sandwip_missing['Year'].value_counts().sort_index())

Total Missing Rows for Sandwip: 1224

--- Sample Dates with Missing Data ---
                   Datetime  Year  Month  Day  Time
2119832 2023-08-01 00:00:00  2023      8    1     0
2119833 2023-08-01 03:00:00  2023      8    1     3
2119834 2023-08-01 06:00:00  2023      8    1     6
2119835 2023-08-01 09:00:00  2023      8    1     9
2119836 2023-08-01 12:00:00  2023      8    1    12
2119837 2023-08-01 15:00:00  2023      8    1    15
2119838 2023-08-01 18:00:00  2023      8    1    18
2119839 2023-08-01 21:00:00  2023      8    1    21
2119840 2023-08-02 00:00:00  2023      8    2     0
2119841 2023-08-02 03:00:00  2023      8    2     3
2119842 2023-08-02 06:00:00  2023      8    2     6
2119843 2023-08-02 09:00:00  2023      8    2     9
2119844 2023-08-02 12:00:00  2023      8    2    12
2119845 2023-08-02 15:00:00  2023      8    2    15
2119846 2023-08-02 18:00:00  2023      8    2    18
2119847 2023-08-02 21:00:00  2023      8    2    21
2119848 2023-08-03 00:00:00  2023      8    3     0
2119849 2023-08-03 03:00:00  2023      8    3     3
2119850 2023-08-03 06:00:00  2023      8    3     6
2119851 2023-08-03 09:00:00  2023      8    3     9
2119852 2023-08-03 12:00:00  2023      8    3    12
2119853 2023-08-03 15:00:00  2023      8    3    15
2119854 2023-08-03 18:00:00  2023      8    3    18
2119855 2023-08-03 21:00:00  2023      8    3    21
2119856 2023-08-04 00:00:00  2023      8    4     0
2119857 2023-08-04 03:00:00  2023      8    4     3
2119858 2023-08-04 06:00:00  2023      8    4     6
2119859 2023-08-04 09:00:00  2023      8    4     9
2119860 2023-08-04 12:00:00  2023      8    4    12
2119861 2023-08-04 15:00:00  2023      8    4    15

--- Years with Missing Data ---
Year
2023    1224
Name: count, dtype: int64

In [108]:
# Filter for Barishal (ID 61360) AND Missing Wind Speed
sandwip_missing = df_rain[
    (df_rain['StationID'] == 11704) &
    (df_rain['SP'].isna())
]

print(f"Total Missing Rows for Sandwip: {len(sandwip_missing)}")

# Show the dates where data is missing
print("\n--- Sample Dates with Missing Data ---")
print(sandwip_missing[['Datetime', 'Year', 'Month', 'Day', 'Time']].head(30))

# Optional: Check if it's a specific block of time (e.g., a whole year)
print("\n--- Years with Missing Data ---")
print(sandwip_missing['Year'].value_counts().sort_index())

Total Missing Rows for Sandwip: 177

--- Sample Dates with Missing Data ---
                 Datetime  Year  Month  Day  Time
61591 2003-01-29 21:00:00  2003      1   29    21
61599 2003-01-30 21:00:00  2003      1   30    21
61607 2003-01-31 21:00:00  2003      1   31    21
62079 2003-03-31 21:00:00  2003      3   31    21
62567 2003-05-31 21:00:00  2003      5   31    21
63303 2003-08-31 21:00:00  2003      8   31    21
63791 2003-10-31 21:00:00  2003     10   31    21
64511 2004-01-29 21:00:00  2004      1   29    21
64519 2004-01-30 21:00:00  2004      1   30    21
64527 2004-01-31 21:00:00  2004      1   31    21
64752 2004-02-29 00:00:00  2004      2   29     0
64753 2004-02-29 03:00:00  2004      2   29     3
64754 2004-02-29 06:00:00  2004      2   29     6
64755 2004-02-29 09:00:00  2004      2   29     9
64756 2004-02-29 12:00:00  2004      2   29    12
64757 2004-02-29 15:00:00  2004      2   29    15
64758 2004-02-29 18:00:00  2004      2   29    18
65007 2004-03-31 21:00:00  2004      3   31    21
65495 2004-05-31 21:00:00  2004      5   31    21
66231 2004-08-31 21:00:00  2004      8   31    21
66719 2004-10-31 21:00:00  2004     10   31    21
67447 2005-01-30 21:00:00  2005      1   30    21
67455 2005-01-31 21:00:00  2005      1   31    21
67927 2005-03-31 21:00:00  2005      3   31    21
68415 2005-05-31 21:00:00  2005      5   31    21
69151 2005-08-31 21:00:00  2005      8   31    21
69639 2005-10-31 21:00:00  2005     10   31    21
70359 2006-01-29 21:00:00  2006      1   29    21
70367 2006-01-30 21:00:00  2006      1   30    21
70375 2006-01-31 21:00:00  2006      1   31    21

--- Years with Missing Data ---
Year
2003     7
2004    14
2005     6
2006     7
2007     7
2008    14
2009     6
2010     7
2011     7
2012    14
2013     6
2014     7
2015     7
2016    14
2017     6
2018     7
2019     7
2020    14
2021     6
2022     7
2023     7
Name: count, dtype: int64

In [109]:
# Drop rows where 'SP' (Wind Speed) is missing
df_rain = df_rain.dropna(subset=['SP','DR'])

# Verify it worked
print(f"Remaining rows: {len(df_rain)}")

Remaining rows: 2116619

In [110]:
df_rain.isna().sum()

StationName             0
Datetime                0
StationID               0
Latitude                0
Longitude               0
Year                    0
Month                   0
Day                     0
Time                    0
Rainfall                0
DewPointTemperature     0
Humidity                0
StationLevelPressure    0
SP                      0
DR                      0
dtype: int64

In [111]:
df_rain

,StationName,Datetime,StationID,Latitude,Longitude,Year,Month,Day,Time,Rainfall,DewPointTemperature,Humidity,StationLevelPressure,SP,DR
0,Ambagan(Ctg.),2003-01-01 00:00:00,41977,22.35,91.82,2003,1,1,0,0.00,12.00,91.00,1009.70,0.00,0.00
1,Ambagan(Ctg.),2003-01-01 03:00:00,41977,22.35,91.82,2003,1,1,3,0.00,13.00,74.00,1011.30,0.00,0.00
2,Ambagan(Ctg.),2003-01-01 06:00:00,41977,22.35,91.82,2003,1,1,6,0.00,15.00,57.00,1011.20,4.00,31.00
3,Ambagan(Ctg.),2003-01-01 09:00:00,41977,22.35,91.82,2003,1,1,9,0.00,9.00,35.00,1010.30,2.00,5.00
4,Ambagan(Ctg.),2003-01-01 12:00:00,41977,22.35,91.82,2003,1,1,12,0.00,13.00,61.00,1010.40,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2119827,Teknaf,2023-07-31 09:00:00,11929,20.87,92.30,2023,7,31,9,0.00,26.00,73.00,1016.00,1.00,10.00
2119828,Teknaf,2023-07-31 12:00:00,11929,20.87,92.30,2023,7,31,12,0.00,26.00,82.00,1016.00,0.00,0.00
2119829,Teknaf,2023-07-31 15:00:00,11929,20.87,92.30,2023,7,31,15,0.00,26.00,88.00,1016.00,0.00,0.00
2119830,Teknaf,2023-07-31 18:00:00,11929,20.87,92.30,2023,7,31,18,0.00,26.00,88.00,1016.00,0.00,0.00
2119831,Teknaf,2023-07-31 21:00:00,11929,20.87,92.30,2023,7,31,21,0.00,25.00,92.00,1016.00,0.00,0.00

In [112]:
# 1. Define your logical column order
new_order = [
    # --- Metadata (Who and When) ---
    'StationID', 'StationName', 'Latitude', 'Longitude',
    'Datetime', 'Year', 'Month', 'Day', 'Time',

    # --- Your Meteorological Variables (Cause -> Effect) ---
    'DewPointTemperature',     # Moisture Content (Absolute)
    'StationLevelPressure',    # Atmospheric Weight
    'SP',                      # Wind Speed (Dynamics)
    'DR',                      # Wind Direction (Dynamics)
    'Humidity',                # Moisture Saturation (Relative)
    'Rainfall'                 # The Result (Precipitation)
]

# 2. Reorder the DataFrame
df_rain = df_rain[new_order]

# 3. Verify the final structure
df_rain

,StationID,StationName,Latitude,Longitude,Datetime,Year,Month,Day,Time,DewPointTemperature,StationLevelPressure,SP,DR,Humidity,Rainfall
0,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 00:00:00,2003,1,1,0,12.00,1009.70,0.00,0.00,91.00,0.00
1,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 03:00:00,2003,1,1,3,13.00,1011.30,0.00,0.00,74.00,0.00
2,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 06:00:00,2003,1,1,6,15.00,1011.20,4.00,31.00,57.00,0.00
3,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 09:00:00,2003,1,1,9,9.00,1010.30,2.00,5.00,35.00,0.00
4,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 12:00:00,2003,1,1,12,13.00,1010.40,0.00,0.00,61.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2119827,11929,Teknaf,20.87,92.30,2023-07-31 09:00:00,2023,7,31,9,26.00,1016.00,1.00,10.00,73.00,0.00
2119828,11929,Teknaf,20.87,92.30,2023-07-31 12:00:00,2023,7,31,12,26.00,1016.00,0.00,0.00,82.00,0.00
2119829,11929,Teknaf,20.87,92.30,2023-07-31 15:00:00,2023,7,31,15,26.00,1016.00,0.00,0.00,88.00,0.00
2119830,11929,Teknaf,20.87,92.30,2023-07-31 18:00:00,2023,7,31,18,26.00,1016.00,0.00,0.00,88.00,0.00
2119831,11929,Teknaf,20.87,92.30,2023-07-31 21:00:00,2023,7,31,21,25.00,1016.00,0.00,0.00,92.00,0.00

# **Adding Primary and Secondary Region to the dataset**

In [113]:
df_rain['StationName'].unique()

array(['Ambagan(Ctg.)', 'Barishal', 'Bhola', 'Bogura', 'Chandpur',
       'Chittagong', 'Chuadanga', "Cox'sBazar", 'Cumilla', 'Dhaka',
       'Dinajpur', 'Faridpur', 'Feni', 'Hatiya', 'Ishurdi', 'Jessore',
       'Khepupara', 'Khulna', 'Kutubdia', 'Madaripur', 'Maijdee_court',
       'Mongla', 'Mymensingh', 'Patuakhali', 'Rajshahi', 'Rangamati',
       'Rangpur', 'Saidpur', 'Sandwip', 'Satkhira', 'Sitakunda',
       'Srimangal', 'Sylhet', 'Tangail', 'Teknaf'], dtype=object)

In [114]:
region_map = {
    # ---------------------------------------------------------
    # REGION 1: NORTH WEST (NW)
    # Characteristics: Driest region. Highest frequency of Dry Thunderstorms.
    # ---------------------------------------------------------
    "Rajshahi":   ("North West", "Inland"),
    "Rangpur":    ("North West", "Inland"),
    "Dinajpur":   ("North West", "Inland"),
    "Saidpur":    ("North West", "Inland"),
    "Bogura":     ("North West", "Inland"),
    "Ishurdi":    ("North West", "Inland"),

    # ---------------------------------------------------------
    # REGION 2: NORTH CENTRAL (NC)
    # Characteristics: Convergence zone of dry & moist air. Urban heat island (Dhaka).
    # ---------------------------------------------------------
    "Dhaka":      ("North Central", "Inland"), # Often considered Urban/Riverine
    "Tangail":    ("North Central", "Inland"),
    "Mymensingh": ("North Central", "Inland"),

    # ---------------------------------------------------------
    # REGION 3: NORTH EAST (NE)
    # Characteristics: Wettest region (Haor basin/Hills). Rare for Dry Storms.
    # ---------------------------------------------------------
    "Sylhet":     ("North East", "Inland"),
    "Srimangal":  ("North East", "Inland"),

    # ---------------------------------------------------------
    # REGION 4: SOUTH WEST (SW)
    # Characteristics: "Moribund Delta". Jessore/Chuadanga are known for extreme heat.
    # ---------------------------------------------------------
    "Jessore":    ("South West", "Inland"),
    "Chuadanga":  ("South West", "Inland"),   # Very hot/dry
    "Khulna":     ("South West", "Riverine"),
    "Satkhira":   ("South West", "Coastal"),  # Near Sundarbans
    "Mongla":     ("South West", "Coastal"),

    # ---------------------------------------------------------
    # REGION 5: SOUTH CENTRAL (SC)
    # Characteristics: "Active Delta". Heavy moisture, riverine dominant.
    # ---------------------------------------------------------
    "Barishal":   ("South Central", "Riverine"),
    "Bhola":      ("South Central", "Coastal"),
    "Patuakhali": ("South Central", "Coastal"),
    "Khepupara":  ("South Central", "Coastal"),
    "Faridpur":   ("South Central", "Riverine"), # Often grouped here due to river path
    "Madaripur":  ("South Central", "Riverine"),

    # ---------------------------------------------------------
    # REGION 6: SOUTH EAST (SE)
    # Characteristics: Maritime/Hilly. Cyclonic path. High humidity.
    # ---------------------------------------------------------
    "Chittagong":    ("South East", "Coastal"),
    "Cox'sBazar":   ("South East", "Coastal"),
    "Teknaf":        ("South East", "Coastal"),
    "Kutubdia":      ("South East", "Coastal"),
    "Sandwip":       ("South East", "Coastal"),
    "Sitakunda":     ("South East", "Coastal"),
    "Ambagan(Ctg.)": ("South East", "Coastal"),
    "Feni":          ("South East", "Inland"),
    "Hatiya":        ("South East", "Coastal"),
    "Maijdee_court": ("South East", "Coastal"),
    "Chandpur":      ("South East", "Riverine"), # Mouth of Meghna
    "Cumilla":       ("South East", "Inland"),
    "Rangamati":     ("South East", "Inland")    # Hill Tracts
}

In [115]:
df_rain[['Primary_Region', 'Secondary_Region']] = (
    df_rain['StationName']
    .map(region_map)
    .apply(pd.Series)
)
df_rain

/tmp/ipython-input-2818763972.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rain[['Primary_Region', 'Secondary_Region']] = (
/tmp/ipython-input-2818763972.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rain[['Primary_Region', 'Secondary_Region']] = (

,StationID,StationName,Latitude,Longitude,Datetime,Year,Month,Day,Time,DewPointTemperature,StationLevelPressure,SP,DR,Humidity,Rainfall,Primary_Region,Secondary_Region
0,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 00:00:00,2003,1,1,0,12.00,1009.70,0.00,0.00,91.00,0.00,South East,Coastal
1,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 03:00:00,2003,1,1,3,13.00,1011.30,0.00,0.00,74.00,0.00,South East,Coastal
2,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 06:00:00,2003,1,1,6,15.00,1011.20,4.00,31.00,57.00,0.00,South East,Coastal
3,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 09:00:00,2003,1,1,9,9.00,1010.30,2.00,5.00,35.00,0.00,South East,Coastal
4,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 12:00:00,2003,1,1,12,13.00,1010.40,0.00,0.00,61.00,0.00,South East,Coastal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2119827,11929,Teknaf,20.87,92.30,2023-07-31 09:00:00,2023,7,31,9,26.00,1016.00,1.00,10.00,73.00,0.00,South East,Coastal
2119828,11929,Teknaf,20.87,92.30,2023-07-31 12:00:00,2023,7,31,12,26.00,1016.00,0.00,0.00,82.00,0.00,South East,Coastal
2119829,11929,Teknaf,20.87,92.30,2023-07-31 15:00:00,2023,7,31,15,26.00,1016.00,0.00,0.00,88.00,0.00,South East,Coastal
2119830,11929,Teknaf,20.87,92.30,2023-07-31 18:00:00,2023,7,31,18,26.00,1016.00,0.00,0.00,88.00,0.00,South East,Coastal
2119831,11929,Teknaf,20.87,92.30,2023-07-31 21:00:00,2023,7,31,21,25.00,1016.00,0.00,0.00,92.00,0.00,South East,Coastal

# **Adding Season**

In [116]:
df_rain["Season"] = df_rain["Month"].map({
        12: "Winter", 1: "Winter", 2: "Winter",
        3: "Pre-Monsoon", 4: "Pre-Monsoon", 5: "Pre-Monsoon",
        6: "Monsoon", 7: "Monsoon", 8: "Monsoon", 9: "Monsoon",
        10: "Post-Monsoon", 11: "Post-Monsoon"
    })
df_rain

/tmp/ipython-input-1713478310.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rain["Season"] = df_rain["Month"].map({

,StationID,StationName,Latitude,Longitude,Datetime,Year,Month,Day,Time,DewPointTemperature,StationLevelPressure,SP,DR,Humidity,Rainfall,Primary_Region,Secondary_Region,Season
0,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 00:00:00,2003,1,1,0,12.00,1009.70,0.00,0.00,91.00,0.00,South East,Coastal,Winter
1,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 03:00:00,2003,1,1,3,13.00,1011.30,0.00,0.00,74.00,0.00,South East,Coastal,Winter
2,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 06:00:00,2003,1,1,6,15.00,1011.20,4.00,31.00,57.00,0.00,South East,Coastal,Winter
3,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 09:00:00,2003,1,1,9,9.00,1010.30,2.00,5.00,35.00,0.00,South East,Coastal,Winter
4,41977,Ambagan(Ctg.),22.35,91.82,2003-01-01 12:00:00,2003,1,1,12,13.00,1010.40,0.00,0.00,61.00,0.00,South East,Coastal,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2119827,11929,Teknaf,20.87,92.30,2023-07-31 09:00:00,2023,7,31,9,26.00,1016.00,1.00,10.00,73.00,0.00,South East,Coastal,Monsoon
2119828,11929,Teknaf,20.87,92.30,2023-07-31 12:00:00,2023,7,31,12,26.00,1016.00,0.00,0.00,82.00,0.00,South East,Coastal,Monsoon
2119829,11929,Teknaf,20.87,92.30,2023-07-31 15:00:00,2023,7,31,15,26.00,1016.00,0.00,0.00,88.00,0.00,South East,Coastal,Monsoon
2119830,11929,Teknaf,20.87,92.30,2023-07-31 18:00:00,2023,7,31,18,26.00,1016.00,0.00,0.00,88.00,0.00,South East,Coastal,Monsoon
2119831,11929,Teknaf,20.87,92.30,2023-07-31 21:00:00,2023,7,31,21,25.00,1016.00,0.00,0.00,92.00,0.00,South East,Coastal,Monsoon

In [117]:
# 1. Define your logical column order
new_order = [
    # --- Metadata (Who and When) ---
    'StationID', 'StationName', 'Latitude', 'Longitude', 'Primary_Region', 'Secondary_Region',
    'Datetime', 'Year', 'Month', 'Day', 'Time',
    'Season',

    # --- Your Meteorological Variables (Cause -> Effect) ---
    'DewPointTemperature',     # Moisture Content (Absolute)
    'StationLevelPressure',    # Atmospheric Weight
    'SP',                      # Wind Speed (Dynamics)
    'DR',                      # Wind Direction (Dynamics)
    'Humidity',                # Moisture Saturation (Relative)
    'Rainfall'                 # The Result (Precipitation)
]

# 2. Reorder the DataFrame
df_rain = df_rain[new_order]

# 3. Verify the final structure
df_rain

,StationID,StationName,Latitude,Longitude,Primary_Region,Secondary_Region,Datetime,Year,Month,Day,Time,Season,DewPointTemperature,StationLevelPressure,SP,DR,Humidity,Rainfall
0,41977,Ambagan(Ctg.),22.35,91.82,South East,Coastal,2003-01-01 00:00:00,2003,1,1,0,Winter,12.00,1009.70,0.00,0.00,91.00,0.00
1,41977,Ambagan(Ctg.),22.35,91.82,South East,Coastal,2003-01-01 03:00:00,2003,1,1,3,Winter,13.00,1011.30,0.00,0.00,74.00,0.00
2,41977,Ambagan(Ctg.),22.35,91.82,South East,Coastal,2003-01-01 06:00:00,2003,1,1,6,Winter,15.00,1011.20,4.00,31.00,57.00,0.00
3,41977,Ambagan(Ctg.),22.35,91.82,South East,Coastal,2003-01-01 09:00:00,2003,1,1,9,Winter,9.00,1010.30,2.00,5.00,35.00,0.00
4,41977,Ambagan(Ctg.),22.35,91.82,South East,Coastal,2003-01-01 12:00:00,2003,1,1,12,Winter,13.00,1010.40,0.00,0.00,61.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2119827,11929,Teknaf,20.87,92.30,South East,Coastal,2023-07-31 09:00:00,2023,7,31,9,Monsoon,26.00,1016.00,1.00,10.00,73.00,0.00
2119828,11929,Teknaf,20.87,92.30,South East,Coastal,2023-07-31 12:00:00,2023,7,31,12,Monsoon,26.00,1016.00,0.00,0.00,82.00,0.00
2119829,11929,Teknaf,20.87,92.30,South East,Coastal,2023-07-31 15:00:00,2023,7,31,15,Monsoon,26.00,1016.00,0.00,0.00,88.00,0.00
2119830,11929,Teknaf,20.87,92.30,South East,Coastal,2023-07-31 18:00:00,2023,7,31,18,Monsoon,26.00,1016.00,0.00,0.00,88.00,0.00
2119831,11929,Teknaf,20.87,92.30,South East,Coastal,2023-07-31 21:00:00,2023,7,31,21,Monsoon,25.00,1016.00,0.00,0.00,92.00,0.00

# **Saving**

In [118]:
# Save the 'df_rain' variable (which has the correct column order and no missing rows)
output_path = '/content/drive/MyDrive/Rainfall/Data/Final processed 3-hourly rainfall data.csv'

df_rain.to_csv(output_path, index=False)

print(f"SUCCESS! File saved to: {output_path}")

SUCCESS! File saved to: /content/drive/MyDrive/Rainfall/Data/Final processed 3-hourly rainfall data.csv